import 'locale_controller.dart';

/// Compact in-app strings for native worker APK (DE/EN/TR/AR/PL/FR/ES/IT).
String t(String key, [String fallback = '']) {
  final lang = LocaleController.instance.lang;
  final row = _strings[key];
  if (row == null) return fallback.isNotEmpty ? fallback : key;
  return row[lang] ?? row['en'] ?? row['de'] ?? (fallback.isNotEmpty ? fallback : key);
}

const Map<String, Map<String, String>> _strings = {
  'navPass': {
    'de': 'Ausweis',
    'en': 'Pass',
    'tr': 'Kart',
    'ar': 'الهوية',
    'pl': 'Karta',
    'fr': 'Badge',
    'es': 'Pase',
    'it': 'Badge',
  },
  'navCheckin': {
    'de': 'Check-in',
    'en': 'Check-in',
    'tr': 'Giriş',
    'ar': 'تسجيل',
    'pl': 'Check-in',
    'fr': 'Pointage',
    'es': 'Entrada',
    'it': 'Check-in',
  },
  'navTasks': {
    'de': 'Aufgaben',
    'en': 'Tasks',
    'tr': 'Görevler',
    'ar': 'المهام',
    'pl': 'Zadania',
    'fr': 'Tâches',
    'es': 'Tareas',
    'it': 'Attività',
  },
  'navChat': {
    'de': 'Chat',
    'en': 'Chat',
    'tr': 'Sohbet',
    'ar': 'محادثة',
    'pl': 'Czat',
    'fr': 'Chat',
    'es': 'Chat',
    'it': 'Chat',
  },
  'navProfile': {
    'de': 'Profil',
    'en': 'Profile',
    'tr': 'Profil',
    'ar': 'الملف',
    'pl': 'Profil',
    'fr': 'Profil',
    'es': 'Perfil',
    'it': 'Profilo',
  },
  'language': {
    'de': 'Sprache',
    'en': 'Language',
    'tr': 'Dil',
    'ar': 'اللغة',
    'pl': 'Język',
    'fr': 'Langue',
    'es': 'Idioma',
    'it': 'Lingua',
  },
  'languageHint': {
    'de': 'Sprache jederzeit hier ändern.',
    'en': 'Change language anytime here.',
    'tr': 'Dili istediğiniz zaman buradan değiştirin.',
    'ar': 'غيّر اللغة في أي وقت من هنا.',
    'pl': 'Zmień język w dowolnym momencie.',
    'fr': 'Changez la langue ici à tout moment.',
    'es': 'Cambia el idioma aquí en cualquier momento.',
    'it': 'Cambia lingua qui in qualsiasi momento.',
  },
  'loginTitle': {
    'de': 'Digitalen Ausweis aktivieren',
    'en': 'Activate digital pass',
    'tr': 'Dijital kartı etkinleştir',
    'ar': 'تفعيل الهوية الرقمية',
    'pl': 'Aktywuj kartę cyfrową',
    'fr': 'Activer le badge numérique',
    'es': 'Activar pase digital',
    'it': 'Attiva badge digitale',
  },
  'loginSubtitle': {
    'de': 'Mitarbeiterausweis',
    'en': 'Employee pass',
    'tr': 'Personel kartı',
    'ar': 'بطاقة الموظف',
    'pl': 'Karta pracownika',
    'fr': 'Badge employé',
    'es': 'Pase de empleado',
    'it': 'Badge dipendente',
  },
  'loginManual': {
    'de': 'Manuell',
    'en': 'Manual',
    'tr': 'Manuel',
    'ar': 'يدوي',
    'pl': 'Ręcznie',
    'fr': 'Manuel',
    'es': 'Manual',
    'it': 'Manuale',
  },
  'loginQr': {
    'de': 'QR-Scan',
    'en': 'QR scan',
    'tr': 'QR tara',
    'ar': 'مسح QR',
    'pl': 'Skan QR',
    'fr': 'Scan QR',
    'es': 'Escanear QR',
    'it': 'Scansiona QR',
  },
  'loginManualTitle': {
    'de': 'Manuelle Anmeldung',
    'en': 'Manual sign-in',
    'tr': 'Manuel giriş',
    'ar': 'تسجيل الدخول اليدوي',
    'pl': 'Logowanie ręczne',
    'fr': 'Connexion manuelle',
    'es': 'Inicio manual',
    'it': 'Accesso manuale',
  },
  'loginManualHint': {
    'de': 'Badge-ID + PIN vom Admin, oder den kompletten Join-Link einfügen.',
    'en': 'Enter Badge-ID + PIN from admin, or paste the full join link.',
    'tr': 'Yöneticiden Badge-ID + PIN girin veya join bağlantısını yapıştırın.',
    'ar': 'أدخل رقم الشارة ورمز PIN من المسؤول، أو الصق رابط التفعيل كاملاً.',
    'pl': 'Wpisz Badge-ID + PIN od admina albo wklej pełny link join.',
    'fr': 'Saisissez Badge-ID + PIN, ou collez le lien d’activation.',
    'es': 'Introduce Badge-ID + PIN, o pega el enlace de activación.',
    'it': 'Inserisci Badge-ID + PIN, oppure incolla il link di attivazione.',
  },
  'loginBadge': {
    'de': 'Badge-ID',
    'en': 'Badge ID',
    'tr': 'Kart ID',
    'ar': 'رقم الشارة',
    'pl': 'ID karty',
    'fr': 'ID badge',
    'es': 'ID de pase',
    'it': 'ID badge',
  },
  'loginPin': {
    'de': 'PIN',
    'en': 'PIN',
    'tr': 'PIN',
    'ar': 'رمز PIN',
    'pl': 'PIN',
    'fr': 'PIN',
    'es': 'PIN',
    'it': 'PIN',
  },
  'loginLink': {
    'de': 'Einmal-Aktivierungslink (optional)',
    'en': 'One-time activation link (optional)',
    'tr': 'Tek kullanımlık link (opsiyonel)',
    'ar': 'رابط التفعيل لمرة واحدة (اختياري)',
    'pl': 'Link aktywacyjny (opcjonalnie)',
    'fr': 'Lien d’activation (optionnel)',
    'es': 'Enlace de activación (opcional)',
    'it': 'Link di attivazione (opzionale)',
  },
  'loginSubmit': {
    'de': 'Anmelden',
    'en': 'Sign in',
    'tr': 'Giriş yap',
    'ar': 'تسجيل الدخول',
    'pl': 'Zaloguj',
    'fr': 'Se connecter',
    'es': 'Iniciar sesión',
    'it': 'Accedi',
  },
  'loginQrTitle': {
    'de': 'Aktivierungs-QR scannen',
    'en': 'Scan activation QR',
    'tr': 'Aktivasyon QR tara',
    'ar': 'امسح رمز التفعيل',
    'pl': 'Zeskanuj QR aktywacji',
    'fr': 'Scanner le QR d’activation',
    'es': 'Escanear QR de activación',
    'it': 'Scansiona QR di attivazione',
  },
  'loginQrHint': {
    'de': 'Kamera erlauben, dann Admin-QR scannen.',
    'en': 'Allow camera, then scan the admin QR.',
    'tr': 'Kameraya izin verin, ardından yönetici QR’sını tarayın.',
    'ar': 'اسمح بالكاميرا ثم امسح رمز المسؤول.',
    'pl': 'Zezwól na kamerę, potem zeskanuj QR admina.',
    'fr': 'Autorisez la caméra, puis scannez le QR admin.',
    'es': 'Permite la cámara y escanea el QR del admin.',
    'it': 'Consenti la fotocamera e scansiona il QR admin.',
  },
  'legal': {
    'de': 'Rechtliches',
    'en': 'Legal',
    'tr': 'Yasal',
    'ar': 'قانوني',
    'pl': 'Informacje prawne',
    'fr': 'Mentions légales',
    'es': 'Legal',
    'it': 'Note legali',
  },
  'privacy': {
    'de': 'Datenschutz',
    'en': 'Privacy',
    'tr': 'Gizlilik',
    'ar': 'الخصوصية',
    'pl': 'Prywatność',
    'fr': 'Confidentialité',
    'es': 'Privacidad',
    'it': 'Privacy',
  },
  'imprint': {
    'de': 'Impressum',
    'en': 'Imprint',
    'tr': 'Künye',
    'ar': 'بيانات الناشر',
    'pl': 'Impressum',
    'fr': 'Mentions',
    'es': 'Aviso legal',
    'it': 'Note legali',
  },
  'cardEmployee': {
    'de': 'MITARBEITERAUSWEIS',
    'en': 'EMPLOYEE PASS',
    'tr': 'PERSONEL KARTI',
    'ar': 'بطاقة الموظف',
    'pl': 'KARTA PRACOWNIKA',
    'fr': 'BADGE EMPLOYÉ',
    'es': 'PASE DE EMPLEADO',
    'it': 'BADGE DIPENDENTE',
  },
  'attachFailed': {
    'de': 'Anhang senden fehlgeschlagen',
    'en': 'Failed to send attachment',
    'tr': 'Ek gönderilemedi',
    'ar': 'فشل إرسال المرفق',
    'pl': 'Nie udało się wysłać załącznika',
    'fr': 'Échec de l’envoi de la pièce jointe',
    'es': 'No se pudo enviar el adjunto',
    'it': 'Invio allegato non riuscito',
  },
  'shiftSwap': {
    'de': 'Schicht tauschen',
    'en': 'Swap shift',
    'tr': 'Vardiya değiştir',
    'ar': 'تبديل الوردية',
    'pl': 'Zamień zmianę',
    'fr': 'Échanger le quart',
    'es': 'Cambiar turno',
    'it': 'Scambia turno',
  },
  'shiftsMine': {
    'de': 'Meine Schichten',
    'en': 'My shifts',
    'tr': 'Vardiyalarım',
    'ar': 'وردياتي',
    'pl': 'Moje zmiany',
    'fr': 'Mes quarts',
    'es': 'Mis turnos',
    'it': 'I miei turni',
  },
  'shiftsSwapTab': {
    'de': 'Tausch',
    'en': 'Swap',
    'tr': 'Değişim',
    'ar': 'تبديل',
    'pl': 'Zamiana',
    'fr': 'Échange',
    'es': 'Cambio',
    'it': 'Scambio',
  },
  'logout': {
    'de': 'Abmelden',
    'en': 'Sign out',
    'tr': 'Çıkış',
    'ar': 'تسجيل الخروج',
    'pl': 'Wyloguj',
    'fr': 'Déconnexion',
    'es': 'Cerrar sesión',
    'it': 'Esci',
  },
  'badge': {
    'de': 'Badge',
    'en': 'Badge',
    'tr': 'Kart',
    'ar': 'الشارة',
    'pl': 'Identyfikator',
    'fr': 'Badge',
    'es': 'Pase',
    'it': 'Badge',
  },
  'role': {
    'de': 'Rolle',
    'en': 'Role',
    'tr': 'Rol',
    'ar': 'الدور',
    'pl': 'Rola',
    'fr': 'Rôle',
    'es': 'Rol',
    'it': 'Ruolo',
  },
  'site': {
    'de': 'Standort',
    'en': 'Site',
    'tr': 'Şantiye',
    'ar': 'الموقع',
    'pl': 'Lokalizacja',
    'fr': 'Chantier',
    'es': 'Obra',
    'it': 'Cantiere',
  },
  'leave': {
    'de': 'Urlaub',
    'en': 'Leave',
    'tr': 'İzin',
    'ar': 'الإجازة',
    'pl': 'Urlop',
    'fr': 'Congés',
    'es': 'Vacaciones',
    'it': 'Ferie',
  },
  'leaveRemaining': {
    'de': 'Verbleibend',
    'en': 'Remaining',
    'tr': 'Kalan',
    'ar': 'المتبقي',
    'pl': 'Pozostało',
    'fr': 'Restant',
    'es': 'Restante',
    'it': 'Rimanenti',
  },
  'leaveTaken': {
    'de': 'Genommen (Jahr)',
    'en': 'Taken (year)',
    'tr': 'Kullanılan (yıl)',
    'ar': 'المستخدم (سنة)',
    'pl': 'Wykorzystane (rok)',
    'fr': 'Pris (année)',
    'es': 'Tomados (año)',
    'it': 'Usati (anno)',
  },
  'days': {
    'de': 'Tage',
    'en': 'days',
    'tr': 'gün',
    'ar': 'أيام',
    'pl': 'dni',
    'fr': 'jours',
    'es': 'días',
    'it': 'giorni',
  },
  'teamOnSite': {
    'de': 'Team vor Ort',
    'en': 'Team on site',
    'tr': 'Sahadaki ekip',
    'ar': 'الفريق في الموقع',
    'pl': 'Zespół na miejscu',
    'fr': 'Équipe sur place',
    'es': 'Equipo en obra',
    'it': 'Squadra in cantiere',
  },
  'present': {
    'de': 'Anwesend',
    'en': 'Present',
    'tr': 'Mevcut',
    'ar': 'الحاضرون',
    'pl': 'Obecni',
    'fr': 'Présents',
    'es': 'Presentes',
    'it': 'Presenti',
  },
  'appUpdates': {
    'de': 'App-Updates',
    'en': 'App updates',
    'tr': 'Uygulama güncellemeleri',
    'ar': 'تحديثات التطبيق',
    'pl': 'Aktualizacje aplikacji',
    'fr': 'Mises à jour',
    'es': 'Actualizaciones',
    'it': 'Aggiornamenti app',
  },
  'pushNotifications': {
    'de': 'Push-Benachrichtigungen',
    'en': 'Push notifications',
    'tr': 'Anlık bildirimler',
    'ar': 'إشعارات الدفع',
    'pl': 'Powiadomienia push',
    'fr': 'Notifications push',
    'es': 'Notificaciones push',
    'it': 'Notifiche push',
  },
  'legalSubtitle': {
    'de': 'Impressum & Datenschutz',
    'en': 'Imprint & privacy',
    'tr': 'Künye ve gizlilik',
    'ar': 'بيانات الناشر والخصوصية',
    'pl': 'Impressum i prywatność',
    'fr': 'Mentions & confidentialité',
    'es': 'Aviso legal y privacidad',
    'it': 'Note legali e privacy',
  },
  'privacySubtitle': {
    'de': 'Erklärung & Firmenkontakt',
    'en': 'Policy & company contact',
    'tr': 'Açıklama ve şirket iletişimi',
    'ar': 'السياسة وتواصل الشركة',
    'pl': 'Polityka i kontakt firmy',
    'fr': 'Politique et contact',
    'es': 'Política y contacto',
    'it': 'Informativa e contatti',
  },
  'checkedInToday': {
    'de': 'Heute eingecheckt',
    'en': 'Checked in today',
    'tr': 'Bugün giriş yapıldı',
    'ar': 'تم التسجيل اليوم',
    'pl': 'Zameldowano dziś',
    'fr': 'Pointé aujourd’hui',
    'es': 'Registrado hoy',
    'it': 'Check-in oggi',
  },
  'notCheckedIn': {
    'de': 'Noch nicht eingecheckt',
    'en': 'Not checked in yet',
    'tr': 'Henüz giriş yapılmadı',
    'ar': 'لم يتم التسجيل بعد',
    'pl': 'Jeszcze nie zameldowano',
    'fr': 'Pas encore pointé',
    'es': 'Aún no registrado',
    'it': 'Non ancora in check-in',
  },
  'constructionSite': {
    'de': 'Baustelle',
    'en': 'Site',
    'tr': 'Şantiye',
    'ar': 'موقع البناء',
    'pl': 'Budowa',
    'fr': 'Chantier',
    'es': 'Obra',
    'it': 'Cantiere',
  },
  'nfcCheckin': {
    'de': 'NFC Check-in / Check-out',
    'en': 'NFC check-in / check-out',
    'tr': 'NFC giriş / çıkış',
    'ar': 'تسجيل الدخول/الخروج بـ NFC',
    'pl': 'NFC check-in / check-out',
    'fr': 'Pointage NFC',
    'es': 'Check-in / out NFC',
    'it': 'Check-in / out NFC',
  },
  'myDeploymentPlan': {
    'de': 'Mein Einsatzplan',
    'en': 'My schedule',
    'tr': 'Görev planım',
    'ar': 'خطة عملي',
    'pl': 'Mój plan pracy',
    'fr': 'Mon planning',
    'es': 'Mi plan',
    'it': 'Il mio piano',
  },
  'walletHint': {
    'de': 'Wallet fürs Gate · QR bleibt Fallback',
    'en': 'Wallet for the gate · QR remains fallback',
    'tr': 'Kapı için cüzdan · QR yedek kalır',
    'ar': 'المحفظة للبوابة · رمز QR كاحتياط',
    'pl': 'Portfel do bramy · QR jako zapas',
    'fr': 'Wallet pour le portail · QR en secours',
    'es': 'Wallet para el acceso · QR de respaldo',
    'it': 'Wallet per il gate · QR di riserva',
  },
  'morningBriefTitle': {
    'de': 'Morgenüberblick',
    'en': 'Morning overview',
    'tr': 'Sabah özeti',
    'ar': 'نظرة الصباح',
    'pl': 'Poranny przegląd',
    'fr': 'Aperçu du matin',
    'es': 'Resumen matutino',
    'it': 'Panoramica mattutina',
  },
  'morningCheckedIn': {
    'de': 'Eingecheckt',
    'en': 'Checked in',
    'tr': 'Giriş yapıldı',
    'ar': 'تم التسجيل',
    'pl': 'Zameldowano',
    'fr': 'Pointé',
    'es': 'Registrado',
    'it': 'In check-in',
  },
  'morningNotCheckedIn': {
    'de': 'Noch nicht eingecheckt',
    'en': 'Not checked in yet',
    'tr': 'Henüz giriş yok',
    'ar': 'لم يتم التسجيل بعد',
    'pl': 'Brak zameldowania',
    'fr': 'Pas encore pointé',
    'es': 'Aún sin registro',
    'it': 'Non ancora in check-in',
  },
  'morningColleagues': {
    'de': '{n} Kollegen vor Ort',
    'en': '{n} colleagues on site',
    'tr': '{n} meslektaş sahada',
    'ar': '{n} زملاء في الموقع',
    'pl': '{n} kolegów na budowie',
    'fr': '{n} collègues sur site',
    'es': '{n} colegas en obra',
    'it': '{n} colleghi in cantiere',
  },
  'morningChat': {
    'de': '{n} Chat ungelesen',
    'en': '{n} unread chat',
    'tr': '{n} okunmamış sohbet',
    'ar': '{n} محادثة غير مقروءة',
    'pl': '{n} nieprzeczytanych czatów',
    'fr': '{n} chat non lus',
    'es': '{n} chats sin leer',
    'it': '{n} chat non lette',
  },
  'morningLeave': {
    'de': '{n} Urlaub offen',
    'en': '{n} leave pending',
    'tr': '{n} izin bekliyor',
    'ar': '{n} إجازة معلّقة',
    'pl': '{n} urlop oczekuje',
    'fr': '{n} congés en attente',
    'es': '{n} vacaciones pendientes',
    'it': '{n} ferie in attesa',
  },
  'morningDocs': {
    'de': '{n} Docs laufen ab',
    'en': '{n} docs expiring',
    'tr': '{n} belge süresi doluyor',
    'ar': '{n} مستندات تنتهي',
    'pl': '{n} docs wygasają',
    'fr': '{n} docs expirent',
    'es': '{n} docs caducan',
    'it': '{n} docs in scadenza',
  },
  'morningGoCheckin': {
    'de': 'Check-in',
    'en': 'Check-in',
    'tr': 'Giriş',
    'ar': 'تسجيل',
    'pl': 'Check-in',
    'fr': 'Pointage',
    'es': 'Entrada',
    'it': 'Check-in',
  },
  'morningGoChat': {
    'de': 'Chat',
    'en': 'Chat',
    'tr': 'Sohbet',
    'ar': 'محادثة',
    'pl': 'Czat',
    'fr': 'Chat',
    'es': 'Chat',
    'it': 'Chat',
  },
  'morningGoDocs': {
    'de': 'Docs / Aufgaben',
    'en': 'Docs / tasks',
    'tr': 'Belgeler / görevler',
    'ar': 'مستندات / مهام',
    'pl': 'Docs / zadania',
    'fr': 'Docs / tâches',
    'es': 'Docs / tareas',
    'it': 'Docs / compiti',
  },
  'toAppleWallet': {
    'de': 'Zu Apple Wallet',
    'en': 'Add to Apple Wallet',
    'tr': 'Apple Wallet’a ekle',
    'ar': 'إضافة إلى Apple Wallet',
    'pl': 'Dodaj do Apple Wallet',
    'fr': 'Ajouter à Apple Wallet',
    'es': 'Añadir a Apple Wallet',
    'it': 'Aggiungi ad Apple Wallet',
  },
  'toGoogleWallet': {
    'de': 'Zu Google Wallet',
    'en': 'Add to Google Wallet',
    'tr': 'Google Wallet’a ekle',
    'ar': 'إضافة إلى Google Wallet',
    'pl': 'Dodaj do Google Wallet',
    'fr': 'Ajouter à Google Wallet',
    'es': 'Añadir a Google Wallet',
    'it': 'Aggiungi a Google Wallet',
  },
  'profileLoadError': {
    'de': 'Profil konnte nicht geladen werden — nach unten ziehen zum Aktualisieren.',
    'en': 'Could not load profile — pull down to refresh.',
    'tr': 'Profil yüklenemedi — yenilemek için aşağı çekin.',
    'ar': 'تعذّر تحميل الملف — اسحب للأسفل للتحديث.',
    'pl': 'Nie udało się wczytać profilu — przeciągnij w dół.',
    'fr': 'Profil introuvable — tirez pour actualiser.',
    'es': 'No se pudo cargar el perfil — desliza para actualizar.',
    'it': 'Profilo non caricato — scorri per aggiornare.',
  },
  'cardActive': {
    'de': 'AKTIV',
    'en': 'ACTIVE',
    'tr': 'AKTİF',
    'ar': 'نشط',
    'pl': 'AKTYWNY',
    'fr': 'ACTIF',
    'es': 'ACTIVO',
    'it': 'ATTIVO',
  },
  'cardBadgeId': {
    'de': 'BADGE-ID',
    'en': 'BADGE ID',
    'tr': 'KART ID',
    'ar': 'رقم الشارة',
    'pl': 'ID KARTY',
    'fr': 'ID BADGE',
    'es': 'ID PASE',
    'it': 'ID BADGE',
  },
  'cardValidUntil': {
    'de': 'GÜLTIG BIS',
    'en': 'VALID UNTIL',
    'tr': 'GEÇERLİLİK',
    'ar': 'صالح حتى',
    'pl': 'WAŻNY DO',
    'fr': 'VALABLE JUSQU’AU',
    'es': 'VÁLIDO HASTA',
    'it': 'VALIDO FINO',
  },
  'cardEmployeeName': {
    'de': 'Mitarbeiter',
    'en': 'Employee',
    'tr': 'Çalışan',
    'ar': 'الموظف',
    'pl': 'Pracownik',
    'fr': 'Employé',
    'es': 'Empleado',
    'it': 'Dipendente',
  },
  'notifications': {
    'de': 'Mitteilungen',
    'en': 'Notifications',
    'tr': 'Bildirimler',
    'ar': 'الإشعارات',
    'pl': 'Powiadomienia',
    'fr': 'Notifications',
    'es': 'Notificaciones',
    'it': 'Notifiche',
  },
  'callEmployer': {
    'de': 'Firma anrufen',
    'en': 'Call company',
    'tr': 'Firmayı ara',
    'ar': 'اتصل بالشركة',
    'pl': 'Zadzwoń do firmy',
    'fr': 'Appeler l’entreprise',
    'es': 'Llamar a la empresa',
    'it': 'Chiama l’azienda',
  },
  'contacts': {
    'de': 'Kontakte',
    'en': 'Contacts',
    'tr': 'Kişiler',
    'ar': 'جهات الاتصال',
    'pl': 'Kontakty',
    'fr': 'Contacts',
    'es': 'Contactos',
    'it': 'Contatti',
  },
  'employer': {
    'de': 'Arbeitgeber',
    'en': 'Employer',
    'tr': 'İşveren',
    'ar': 'صاحب العمل',
    'pl': 'Pracodawca',
    'fr': 'Employeur',
    'es': 'Empleador',
    'it': 'Datore',
  },
  'chatShowOriginal': {
    'de': 'Original anzeigen',
    'en': 'Show original',
    'tr': 'Orijinali göster',
    'ar': 'إظهار النص الأصلي',
    'pl': 'Pokaż oryginał',
    'fr': 'Afficher l’original',
    'es': 'Mostrar original',
    'it': 'Mostra originale',
  },
  'chatShowTranslation': {
    'de': 'Übersetzung anzeigen',
    'en': 'Show translation',
    'tr': 'Çeviriyi göster',
    'ar': 'إظهار الترجمة',
    'pl': 'Pokaż tłumaczenie',
    'fr': 'Afficher la traduction',
    'es': 'Mostrar traducción',
    'it': 'Mostra traduzione',
  },
  'chatTranslated': {
    'de': 'Übersetzt',
    'en': 'Translated',
    'tr': 'Çevrildi',
    'ar': 'مترجم',
    'pl': 'Przetłumaczono',
    'fr': 'Traduit',
    'es': 'Traducido',
    'it': 'Tradotto',
  },
  'chatReply': {
    'de': 'Antworten',
    'en': 'Reply',
    'tr': 'Yanıtla',
    'ar': 'رد',
    'pl': 'Odpowiedz',
    'fr': 'Répondre',
    'es': 'Responder',
    'it': 'Rispondi',
  },
  'chatCopy': {
    'de': 'Kopieren',
    'en': 'Copy',
    'tr': 'Kopyala',
    'ar': 'نسخ',
    'pl': 'Kopiuj',
    'fr': 'Copier',
    'es': 'Copiar',
    'it': 'Copia',
  },
  'chatCopied': {
    'de': 'Kopiert',
    'en': 'Copied',
    'tr': 'Kopyalandı',
    'ar': 'تم النسخ',
    'pl': 'Skopiowano',
    'fr': 'Copié',
    'es': 'Copiado',
    'it': 'Copiato',
  },
  'chatPin': {
    'de': 'Anheften',
    'en': 'Pin',
    'tr': 'Sabitle',
    'ar': 'تثبيت',
    'pl': 'Przypnij',
    'fr': 'Épingler',
    'es': 'Fijar',
    'it': 'Fissa',
  },
  'chatUnpin': {
    'de': 'Loslösen',
    'en': 'Unpin',
    'tr': 'Kaldır',
    'ar': 'إلغاء التثبيت',
    'pl': 'Odepnij',
    'fr': 'Désépingler',
    'es': 'Desfijar',
    'it': 'Sblocca',
  },
  'chatStar': {
    'de': 'Mit Stern markieren',
    'en': 'Star',
    'tr': 'Yıldızla',
    'ar': 'تمييز بنجمة',
    'pl': 'Oznacz gwiazdką',
    'fr': 'Favori',
    'es': 'Destacar',
    'it': 'Preferito',
  },
  'chatUnstar': {
    'de': 'Stern entfernen',
    'en': 'Remove star',
    'tr': 'Yıldızı kaldır',
    'ar': 'إزالة النجمة',
    'pl': 'Usuń gwiazdkę',
    'fr': 'Retirer le favori',
    'es': 'Quitar destacado',
    'it': 'Rimuovi preferito',
  },
  'chatDelete': {
    'de': 'Löschen',
    'en': 'Delete',
    'tr': 'Sil',
    'ar': 'حذف',
    'pl': 'Usuń',
    'fr': 'Supprimer',
    'es': 'Eliminar',
    'it': 'Elimina',
  },
  'chatDeleteFailed': {
    'de': 'Löschen fehlgeschlagen',
    'en': 'Delete failed',
    'tr': 'Silinemedi',
    'ar': 'فشل الحذف',
    'pl': 'Usuwanie nieudane',
    'fr': 'Échec de suppression',
    'es': 'Error al eliminar',
    'it': 'Eliminazione non riuscita',
  },
  'splashTagline': {
    'de': 'Mitarbeiter-App',
    'en': 'Employee app',
    'tr': 'Personel uygulaması',
    'ar': 'تطبيق الموظف',
    'pl': 'Aplikacja pracownika',
    'fr': 'App employé',
    'es': 'App de empleado',
    'it': 'App dipendente',
  },
  'helloName': {
    'de': 'Hallo, {name}',
    'en': 'Hello, {name}',
    'tr': 'Merhaba, {name}',
    'ar': 'مرحباً، {name}',
    'pl': 'Cześć, {name}',
    'fr': 'Bonjour, {name}',
    'es': 'Hola, {name}',
    'it': 'Ciao, {name}',
  },
  'todayHours': {
    'de': 'Heute: {h}',
    'en': 'Today: {h}',
    'tr': 'Bugün: {h}',
    'ar': 'اليوم: {h}',
    'pl': 'Dziś: {h}',
    'fr': "Aujourd'hui : {h}",
    'es': 'Hoy: {h}',
    'it': 'Oggi: {h}',
  },
  'todayHoursOpen': {
    'de': 'Heute: {h} (eingestempelt)',
    'en': 'Today: {h} (clocked in)',
    'tr': 'Bugün: {h} (giriş yapılmış)',
    'ar': 'اليوم: {h} (مسجّل دخول)',
    'pl': 'Dziś: {h} (zalogowany)',
    'fr': "Aujourd'hui : {h} (pointé)",
    'es': 'Hoy: {h} (fichado)',
    'it': 'Oggi: {h} (in ingresso)',
  },
  'openTimesheet': {
    'de': 'Stundennachweis öffnen',
    'en': 'Open timesheet',
    'tr': 'Puantajı aç',
    'ar': 'فتح سجل الساعات',
    'pl': 'Otwórz ewidencję',
    'fr': 'Ouvrir le relevé',
    'es': 'Abrir parte de horas',
    'it': 'Apri foglio ore',
  },
  'gpsNoNfcTitle': {
    'de': 'GPS ohne NFC',
    'en': 'GPS without NFC',
    'tr': 'NFC olmadan GPS',
    'ar': 'GPS بدون NFC',
    'pl': 'GPS bez NFC',
    'fr': 'GPS sans NFC',
    'es': 'GPS sin NFC',
    'it': 'GPS senza NFC',
  },
  'gpsNoNfcHint': {
    'de': 'Ein- oder ausstempeln auf der Baustelle (ohne NFC-Karte).',
    'en': 'Clock in or out on site (without NFC card).',
    'tr': 'Sahada giriş/çıkış (NFC kartı olmadan).',
    'ar': 'تسجيل الدخول أو الخروج في الموقع (بدون بطاقة NFC).',
    'pl': 'Wejście/wyjście na budowie (bez karty NFC).',
    'fr': 'Pointer sur le chantier (sans carte NFC).',
    'es': 'Fichar en obra (sin tarjeta NFC).',
    'it': 'Timbratura in cantiere (senza carta NFC).',
  },
  'gpsCheckinAuto': {
    'de': 'GPS — Anmelden / Abmelden',
    'en': 'GPS — Check in / out',
    'tr': 'GPS — Giriş / çıkış',
    'ar': 'GPS — تسجيل دخول / خروج',
    'pl': 'GPS — Wejście / wyjście',
    'fr': 'GPS — Entrée / sortie',
    'es': 'GPS — Entrada / salida',
    'it': 'GPS — Entrata / uscita',
  },
  'gpsIn': {
    'de': 'Ein',
    'en': 'In',
    'tr': 'Giriş',
    'ar': 'دخول',
    'pl': 'Wejście',
    'fr': 'Entrée',
    'es': 'Entrada',
    'it': 'Entrata',
  },
  'gpsOut': {
    'de': 'Aus',
    'en': 'Out',
    'tr': 'Çıkış',
    'ar': 'خروج',
    'pl': 'Wyjście',
    'fr': 'Sortie',
    'es': 'Salida',
    'it': 'Uscita',
  },
  'nfcGateTitle': {
    'de': 'NFC am Bauzaun',
    'en': 'NFC at the gate',
    'tr': 'Kapıda NFC',
    'ar': 'NFC عند البوابة',
    'pl': 'NFC przy bramie',
    'fr': 'NFC au portail',
    'es': 'NFC en el acceso',
    'it': 'NFC al cancello',
  },
  'nfcGateHint': {
    'de': '1. Physische Karte am Gate-Reader (empfohlen bei schlechtem Netz).\n2. Oder NFC hier scannen — offline zwischengespeichert, später synchronisiert.',
    'en': '1. Physical card at the gate reader (recommended on poor network).\n2. Or scan NFC here — stored offline, synced later.',
    'tr': '1. Kapı okuyucuda fiziksel kart (zayıf ağda önerilir).\n2. Veya burada NFC tarayın — çevrimdışı kaydedilir, sonra senkronize edilir.',
    'ar': '1. البطاقة الفعلية عند قارئ البوابة (موصى به عند ضعف الشبكة).\n2. أو امسح NFC هنا — يُحفظ دون اتصال ويُزامن لاحقاً.',
    'pl': '1. Fizyczna karta przy czytniku (zalecane przy słabej sieci).\n2. Lub zeskanuj NFC tutaj — zapis offline, synchronizacja później.',
    'fr': '1. Carte physique au lecteur (recommandé si réseau faible).\n2. Ou scannez le NFC ici — stocké hors ligne, synchronisé plus tard.',
    'es': '1. Tarjeta física en el lector (recomendado con mala red).\n2. O escanea NFC aquí — se guarda sin conexión y se sincroniza después.',
    'it': '1. Carta fisica al lettore (consigliato con rete scarsa).\n2. Oppure scansiona NFC qui — salvato offline, sincronizzato dopo.',
  },
  'badgeIdLabel': {
    'de': 'Badge-ID: {id}',
    'en': 'Badge ID: {id}',
    'tr': 'Kart ID: {id}',
    'ar': 'معرّف الشارة: {id}',
    'pl': 'ID karty: {id}',
    'fr': 'ID badge : {id}',
    'es': 'ID del pase: {id}',
    'it': 'ID badge: {id}',
  },
  'lastAction': {
    'de': 'Letzte Aktion: {dir}',
    'en': 'Last action: {dir}',
    'tr': 'Son işlem: {dir}',
    'ar': 'آخر إجراء: {dir}',
    'pl': 'Ostatnia akcja: {dir}',
    'fr': 'Dernière action : {dir}',
    'es': 'Última acción: {dir}',
    'it': 'Ultima azione: {dir}',
  },
  'nfcScanButton': {
    'de': 'NFC — Check-in/out',
    'en': 'NFC — Check-in/out',
    'tr': 'NFC — Giriş/çıkış',
    'ar': 'NFC — تسجيل دخول/خروج',
    'pl': 'NFC — Wejście/wyjście',
    'fr': 'NFC — Pointage',
    'es': 'NFC — Entrada/salida',
    'it': 'NFC — Check-in/out',
  },
  'scanning': {
    'de': 'Scanne…',
    'en': 'Scanning…',
    'tr': 'Taranıyor…',
    'ar': 'جارٍ المسح…',
    'pl': 'Skanowanie…',
    'fr': 'Scan…',
    'es': 'Escaneando…',
    'it': 'Scansione…',
  },
  'locating': {
    'de': 'Standort wird ermittelt…',
    'en': 'Getting location…',
    'tr': 'Konum alınıyor…',
    'ar': 'جاري تحديد الموقع…',
    'pl': 'Pobieranie lokalizacji…',
    'fr': 'Localisation…',
    'es': 'Obteniendo ubicación…',
    'it': 'Posizione in corso…',
  },
  'holdNfc': {
    'de': 'NFC-Karte ans Handy halten…',
    'en': 'Hold NFC card to phone…',
    'tr': 'NFC kartını telefona tutun…',
    'ar': 'أمسك بطاقة NFC بالهاتف…',
    'pl': 'Przyłóż kartę NFC do telefonu…',
    'fr': 'Approchez la carte NFC…',
    'es': 'Acerca la tarjeta NFC…',
    'it': 'Avvicina la carta NFC…',
  },
  'sendingCheckin': {
    'de': 'Check-in wird gesendet…',
    'en': 'Sending check-in…',
    'tr': 'Giriş gönderiliyor…',
    'ar': 'جارٍ إرسال التسجيل…',
    'pl': 'Wysyłanie check-in…',
    'fr': 'Envoi du pointage…',
    'es': 'Enviando fichaje…',
    'it': 'Invio check-in…',
  },
  'attendanceSaved': {
    'de': 'Anwesenheit gespeichert: {dir}',
    'en': 'Attendance saved: {dir}',
    'tr': 'Devam kaydedildi: {dir}',
    'ar': 'تم حفظ الحضور: {dir}',
    'pl': 'Obecność zapisana: {dir}',
    'fr': 'Présence enregistrée : {dir}',
    'es': 'Asistencia guardada: {dir}',
    'it': 'Presenza salvata: {dir}',
  },
  'attendanceDuplicate': {
    'de': 'Bereits erfasst ({dir}).',
    'en': 'Already recorded ({dir}).',
    'tr': 'Zaten kaydedildi ({dir}).',
    'ar': 'مسجّل مسبقاً ({dir}).',
    'pl': 'Już zapisano ({dir}).',
    'fr': 'Déjà enregistré ({dir}).',
    'es': 'Ya registrado ({dir}).',
    'it': 'Già registrato ({dir}).',
  },
  'offlineQueued': {
    'de': 'Offline gespeichert ({dir}) — wird synchronisiert.',
    'en': 'Saved offline ({dir}) — will sync.',
    'tr': 'Çevrimdışı kaydedildi ({dir}) — senkronize edilecek.',
    'ar': 'حُفظ دون اتصال ({dir}) — ستتم المزامنة.',
    'pl': 'Zapisano offline ({dir}) — zostanie zsynchronizowane.',
    'fr': 'Enregistré hors ligne ({dir}) — synchronisation à venir.',
    'es': 'Guardado sin conexión ({dir}) — se sincronizará.',
    'it': 'Salvato offline ({dir}) — verrà sincronizzato.',
  },
  'offlineProfile': {
    'de': 'Offline — zwischengespeichertes Profil.',
    'en': 'Offline — cached profile.',
    'tr': 'Çevrimdışı — önbellek profil.',
    'ar': 'دون اتصال — ملف مخزّن مؤقتاً.',
    'pl': 'Offline — profil z pamięci podręcznej.',
    'fr': 'Hors ligne — profil en cache.',
    'es': 'Sin conexión — perfil en caché.',
    'it': 'Offline — profilo in cache.',
  },
  'offlineSync': {
    'de': 'Offline-Sync',
    'en': 'Offline sync',
    'tr': 'Çevrimdışı senkron',
    'ar': 'مزامنة دون اتصال',
    'pl': 'Synchronizacja offline',
    'fr': 'Sync hors ligne',
    'es': 'Sincronizar offline',
    'it': 'Sync offline',
  },
  'gpsOff': {
    'de': 'GPS ist am Handy aus — bitte Standort aktivieren.',
    'en': 'GPS is off — please enable location.',
    'tr': 'GPS kapalı — lütfen konumu açın.',
    'ar': 'GPS متوقف — يرجى تفعيل الموقع.',
    'pl': 'GPS wyłączony — włącz lokalizację.',
    'fr': 'GPS désactivé — activez la localisation.',
    'es': 'GPS apagado — active la ubicación.',
    'it': 'GPS spento — attiva la posizione.',
  },
  'gpsPermissionDenied': {
    'de': 'Standortfreigabe fehlt — bitte „Beim Verwenden der App“ erlauben.',
    'en': 'Location permission missing — allow “While using the app”.',
    'tr': 'Konum izni yok — “Uygulamayı kullanırken” izin verin.',
    'ar': 'إذن الموقع مفقود — اسمح بـ «أثناء استخدام التطبيق».',
    'pl': 'Brak uprawnień do lokalizacji — zezwól „Podczas używania”.',
    'fr': 'Autorisation manquante — autorisez « Pendant l’utilisation ».',
    'es': 'Falta permiso de ubicación — permita «Al usar la app».',
    'it': 'Permesso posizione mancante — consenti «Durante l’uso».',
  },
  'gpsPermissionForever': {
    'de': 'Standort dauerhaft blockiert — in Android-Einstellungen für SUPPIX erlauben.',
    'en': 'Location blocked permanently — allow it in Android settings for SUPPIX.',
    'tr': 'Konum kalıcı engelli — Android ayarlarından SUPPIX için izin verin.',
    'ar': 'الموقع محظور نهائياً — اسمح به في إعدادات Android لـ SUPPIX.',
    'pl': 'Lokalizacja zablokowana — zezwól w ustawieniach Androida dla SUPPIX.',
    'fr': 'Localisation bloquée — autorisez-la dans les réglages Android pour SUPPIX.',
    'es': 'Ubicación bloqueada — permítala en ajustes de Android para SUPPIX.',
    'it': 'Posizione bloccata — consenti nelle impostazioni Android per SUPPIX.',
  },
  'gpsSlowOrInaccurate': {
    'de': 'Standort zu langsam / ungenau — kurz warten und erneut tippen.',
    'en': 'Location too slow / inaccurate — wait a moment and try again.',
    'tr': 'Konum yavaş / hatalı — biraz bekleyip tekrar deneyin.',
    'ar': 'الموقع بطيء / غير دقيق — انتظر قليلاً وحاول مجدداً.',
    'pl': 'Lokalizacja zbyt wolna / niedokładna — poczekaj i spróbuj ponownie.',
    'fr': 'Localisation trop lente / imprécise — attendez et réessayez.',
    'es': 'Ubicación lenta / imprecisa — espere y vuelva a intentarlo.',
    'it': 'Posizione lenta / imprecisa — attendi e riprova.',
  },
  'gpsCaptureFailed': {
    'de': 'Standort konnte nicht ermittelt werden — GPS prüfen und erneut tippen.',
    'en': 'Could not get location — check GPS and try again.',
    'tr': 'Konum alınamadı — GPS’i kontrol edip tekrar deneyin.',
    'ar': 'تعذّر تحديد الموقع — تحقق من GPS وحاول مجدداً.',
    'pl': 'Nie udało się pobrać lokalizacji — sprawdź GPS i spróbuj ponownie.',
    'fr': 'Impossible d’obtenir la position — vérifiez le GPS et réessayez.',
    'es': 'No se pudo obtener la ubicación — revise el GPS e inténtelo de nuevo.',
    'it': 'Impossibile ottenere la posizione — controlla il GPS e riprova.',
  },
  'gpsRequired': {
    'de': 'GPS erforderlich — Standortfreigabe aktivieren.',
    'en': 'GPS required — enable location permission.',
    'tr': 'GPS gerekli — konum iznini açın.',
    'ar': 'GPS مطلوب — فعّل إذن الموقع.',
    'pl': 'Wymagany GPS — włącz uprawnienie lokalizacji.',
    'fr': 'GPS requis — activez la localisation.',
    'es': 'Se requiere GPS — active el permiso de ubicación.',
    'it': 'GPS richiesto — attiva il permesso posizione.',
  },
  'errOutsideGeofence': {
    'de': 'Außerhalb der Baustelle — Check-in nur vor Ort möglich.',
    'en': 'Outside the site — check-in only on site.',
    'tr': 'Şantiye dışında — giriş yalnızca sahada mümkün.',
    'ar': 'خارج الموقع — التسجيل فقط في الموقع.',
    'pl': 'Poza budową — check-in tylko na miejscu.',
    'fr': 'Hors chantier — pointage uniquement sur site.',
    'es': 'Fuera de obra — fichaje solo en el sitio.',
    'it': 'Fuori cantiere — check-in solo in loco.',
  },
  'errSiteLocationUnavailable': {
    'de': 'Baustelle hat keinen GPS-Standort — Admin muss Standort in Firmeneinstellungen setzen.',
    'en': 'Site has no GPS location — admin must set it in company settings.',
    'tr': 'Şantiyenin GPS konumu yok — yönetici firma ayarlarından eklemeli.',
    'ar': 'الموقع بلا إحداثيات GPS — يجب على المسؤول ضبطها في إعدادات الشركة.',
    'pl': 'Budowa bez lokalizacji GPS — admin musi ustawić ją w firmie.',
    'fr': 'Chantier sans GPS — l’admin doit le définir dans les paramètres.',
    'es': 'Obra sin GPS — el admin debe configurarlo en la empresa.',
    'it': 'Cantiere senza GPS — l’admin deve impostarlo in azienda.',
  },
  'errGpsInaccurate': {
    'de': 'GPS zu ungenau — kurz warten und erneut versuchen.',
    'en': 'GPS too inaccurate — wait a moment and try again.',
    'tr': 'GPS çok hatalı — biraz bekleyip tekrar deneyin.',
    'ar': 'GPS غير دقيق — انتظر قليلاً وحاول مجدداً.',
    'pl': 'GPS zbyt niedokładny — poczekaj i spróbuj ponownie.',
    'fr': 'GPS trop imprécis — attendez et réessayez.',
    'es': 'GPS demasiado impreciso — espere y vuelva a intentarlo.',
    'it': 'GPS troppo impreciso — attendi e riprova.',
  },
  'errNfcNotEnrolled': {
    'de': 'NFC-Karte nicht hinterlegt — Admin muss die Karte dem Mitarbeiter zuweisen.',
    'en': 'NFC card not enrolled — admin must assign the card to the worker.',
    'tr': 'NFC kartı kayıtlı değil — yönetici karta atamalı.',
    'ar': 'بطاقة NFC غير مسجّلة — يجب على المسؤول تعيينها للموظف.',
    'pl': 'Karta NFC nieprzypisana — admin musi ją przypisać.',
    'fr': 'Carte NFC non enregistrée — l’admin doit l’assigner.',
    'es': 'Tarjeta NFC no registrada — el admin debe asignarla.',
    'it': 'Carta NFC non registrata — l’admin deve assegnarla.',
  },
  'errNfcMismatch': {
    'de': 'Falsche NFC-Karte — bitte die zugewiesene Mitarbeiterkarte verwenden.',
    'en': 'Wrong NFC card — use the assigned employee card.',
    'tr': 'Yanlış NFC kartı — atanmış personel kartını kullanın.',
    'ar': 'بطاقة NFC خاطئة — استخدم بطاقة الموظف المعيّنة.',
    'pl': 'Zła karta NFC — użyj przypisanej karty pracownika.',
    'fr': 'Mauvaise carte NFC — utilisez la carte assignée.',
    'es': 'Tarjeta NFC incorrecta — use la tarjeta asignada.',
    'it': 'Carta NFC errata — usa la carta dipendente assegnata.',
  },
  'errDeviceNotBound': {
    'de': 'Gerät nicht freigegeben — bitte erneut anmelden.',
    'en': 'Device not authorized — please sign in again.',
    'tr': 'Cihaz yetkili değil — lütfen yeniden giriş yapın.',
    'ar': 'الجهاز غير مصرّح — يرجى تسجيل الدخول مجدداً.',
    'pl': 'Urządzenie nieautoryzowane — zaloguj się ponownie.',
    'fr': 'Appareil non autorisé — reconnectez-vous.',
    'es': 'Dispositivo no autorizado — inicie sesión de nuevo.',
    'it': 'Dispositivo non autorizzato — accedi di nuovo.',
  },
  'errNetwork': {
    'de': 'Keine Verbindung zum Server — Internet prüfen.',
    'en': 'No server connection — check internet.',
    'tr': 'Sunucu bağlantısı yok — interneti kontrol edin.',
    'ar': 'لا اتصال بالخادم — تحقق من الإنترنت.',
    'pl': 'Brak połączenia z serwerem — sprawdź internet.',
    'fr': 'Pas de connexion serveur — vérifiez Internet.',
    'es': 'Sin conexión al servidor — revise Internet.',
    'it': 'Nessuna connessione al server — controlla Internet.',
  },
  'errAlreadyCheckedIn': {
    'de': 'Bereits eingestempelt — bitte erst ausstempeln.',
    'en': 'Already checked in — please check out first.',
    'tr': 'Zaten giriş yapılmış — önce çıkış yapın.',
    'ar': 'مسجّل دخول مسبقاً — سجّل الخروج أولاً.',
    'pl': 'Już zameldowano — najpierw wymelduj się.',
    'fr': 'Déjà pointé — veuillez d’abord sortir.',
    'es': 'Ya fichado — primero registre la salida.',
    'it': 'Già in ingresso — prima effettua l’uscita.',
  },
  'errNotCheckedIn': {
    'de': 'Nicht eingestempelt — bitte zuerst einchecken.',
    'en': 'Not checked in — please check in first.',
    'tr': 'Giriş yok — önce giriş yapın.',
    'ar': 'غير مسجّل دخول — سجّل الدخول أولاً.',
    'pl': 'Brak zameldowania — najpierw check-in.',
    'fr': 'Pas pointé — veuillez d’abord entrer.',
    'es': 'Sin fichaje — primero registre la entrada.',
    'it': 'Non in ingresso — prima effettua il check-in.',
  },
  'nfcUnavailable': {
    'de': 'NFC nicht verfügbar — in den Einstellungen aktivieren.',
    'en': 'NFC unavailable — enable it in settings.',
    'tr': 'NFC yok — ayarlardan açın.',
    'ar': 'NFC غير متاح — فعّله من الإعدادات.',
    'pl': 'NFC niedostępne — włącz w ustawieniach.',
    'fr': 'NFC indisponible — activez-le dans les réglages.',
    'es': 'NFC no disponible — actívelo en ajustes.',
    'it': 'NFC non disponibile — attivalo nelle impostazioni.',
  },
  'errOutsideGeofenceDistance': {
    'de': 'Außerhalb der Baustelle ({dist} m, erlaubt {radius} m) — näher herangehen.',
    'en': 'Outside the site ({dist} m, allowed {radius} m) — move closer.',
    'tr': 'Şantiye dışında ({dist} m, izin {radius} m) — yaklaşın.',
    'ar': 'خارج الموقع ({dist} م، المسموح {radius} م) — اقترب أكثر.',
    'pl': 'Poza budową ({dist} m, dozwolone {radius} m) — podejdź bliżej.',
    'fr': 'Hors chantier ({dist} m, autorisé {radius} m) — rapprochez-vous.',
    'es': 'Fuera de obra ({dist} m, permitido {radius} m) — acérquese.',
    'it': 'Fuori cantiere ({dist} m, consentiti {radius} m) — avvicinati.',
  },
  'tabPlan': {
    'de': 'Einsatzplan',
    'en': 'Schedule',
    'tr': 'Plan',
    'ar': 'الخطة',
    'pl': 'Plan',
    'fr': 'Planning',
    'es': 'Plan',
    'it': 'Piano',
  },
  'tabLeave': {
    'de': 'Urlaub',
    'en': 'Leave',
    'tr': 'İzin',
    'ar': 'إجازة',
    'pl': 'Urlop',
    'fr': 'Congés',
    'es': 'Vacaciones',
    'it': 'Ferie',
  },
  'tabDocs': {
    'de': 'Dokumente',
    'en': 'Documents',
    'tr': 'Belgeler',
    'ar': 'المستندات',
    'pl': 'Dokumenty',
    'fr': 'Documents',
    'es': 'Documentos',
    'it': 'Documenti',
  },
  'tabContracts': {
    'de': 'Verträge',
    'en': 'Contracts',
    'tr': 'Sözleşmeler',
    'ar': 'العقود',
    'pl': 'Umowy',
    'fr': 'Contrats',
    'es': 'Contratos',
    'it': 'Contratti',
  },
  'tabShifts': {
    'de': 'Schichten',
    'en': 'Shifts',
    'tr': 'Vardiyalar',
    'ar': 'الورديات',
    'pl': 'Zmiany',
    'fr': 'Équipes',
    'es': 'Turnos',
    'it': 'Turni',
  },
  'timesheetTitle': {
    'de': 'Stundennachweis',
    'en': 'Timesheet',
    'tr': 'Puantaj',
    'ar': 'سجل الساعات',
    'pl': 'Ewidencja czasu',
    'fr': 'Relevé d’heures',
    'es': 'Parte de horas',
    'it': 'Foglio ore',
  },
  'reload': {
    'de': 'Erneut laden',
    'en': 'Reload',
    'tr': 'Yeniden yükle',
    'ar': 'إعادة التحميل',
    'pl': 'Załaduj ponownie',
    'fr': 'Recharger',
    'es': 'Recargar',
    'it': 'Ricarica',
  },
  'monthTotal': {
    'de': 'Monat gesamt',
    'en': 'Month total',
    'tr': 'Ay toplamı',
    'ar': 'إجمالي الشهر',
    'pl': 'Suma miesiąca',
    'fr': 'Total du mois',
    'es': 'Total del mes',
    'it': 'Totale mese',
  },
  'events': {
    'de': 'Ereignisse',
    'en': 'Events',
    'tr': 'Olaylar',
    'ar': 'الأحداث',
    'pl': 'Zdarzenia',
    'fr': 'Événements',
    'es': 'Eventos',
    'it': 'Eventi',
  },
  'noEntriesMonth': {
    'de': 'Keine Einträge in diesem Monat.',
    'en': 'No entries this month.',
    'tr': 'Bu ay kayıt yok.',
    'ar': 'لا إدخالات هذا الشهر.',
    'pl': 'Brak wpisów w tym miesiącu.',
    'fr': 'Aucune entrée ce mois-ci.',
    'es': 'Sin entradas este mes.',
    'it': 'Nessuna voce questo mese.',
  },
  'errOnLeave': {
    'de': 'Heute genehmigter Urlaub — Check-in nicht möglich.',
    'en': 'Approved leave today — check-in not possible.',
    'tr': 'Bugün onaylı izin — giriş yapılamaz.',
    'ar': 'إجازة معتمدة اليوم — لا يمكن التسجيل.',
    'pl': 'Dziś zatwierdzony urlop — brak check-in.',
    'fr': 'Congé approuvé aujourd’hui — pointage impossible.',
    'es': 'Vacaciones aprobadas hoy — no se puede fichar.',
    'it': 'Ferie approvate oggi — check-in non possibile.',
  },
  'errDeploymentDeclined': {
    'de': 'Einsatztag abgelehnt — Check-in nicht möglich.',
    'en': 'Assignment declined — check-in not possible.',
    'tr': 'Görev günü reddedildi — giriş yapılamaz.',
    'ar': 'تم رفض يوم التكليف — لا يمكن التسجيل.',
    'pl': 'Dzień pracy odrzucony — brak check-in.',
    'fr': 'Jour d’affectation refusé — pointage impossible.',
    'es': 'Día de asignación rechazado — no se puede fichar.',
    'it': 'Giorno di incarico rifiutato — check-in non possibile.',
  },
  'attendanceOutsideHoursOk': {
    'de': 'Gespeichert außerhalb der Schichtzeit — Arbeitgeber wurde informiert.',
    'en': 'Saved outside shift hours — employer was notified.',
    'tr': 'Vardiya dışında kaydedildi — işveren bilgilendirildi.',
    'ar': 'حُفظ خارج وقت الوردية — تم إبلاغ صاحب العمل.',
    'pl': 'Zapisano poza godzinami zmiany — pracodawca powiadomiony.',
    'fr': 'Enregistré hors créneau — employeur informé.',
    'es': 'Guardado fuera del turno — empleador notificado.',
    'it': 'Salvato fuori orario — datore di lavoro avvisato.',
  },
  'notificationsNew': {
    'de': '{n} neu',
    'en': '{n} new',
    'tr': '{n} yeni',
    'ar': '{n} جديد',
    'pl': '{n} nowe',
    'fr': '{n} nouv.',
    'es': '{n} nuev.',
    'it': '{n} nuov.',
  },
  'notificationsEmpty': {
    'de': 'Keine Mitteilungen',
    'en': 'No notifications',
    'tr': 'Bildirim yok',
    'ar': 'لا إشعارات',
    'pl': 'Brak powiadomień',
    'fr': 'Aucune notification',
    'es': 'Sin notificaciones',
    'it': 'Nessuna notifica',
  },
  'privacyNoticeTitle': {
    'de': 'Datenschutzhinweis',
    'en': 'Privacy notice',
    'tr': 'Gizlilik bildirimi',
    'ar': 'إشعار الخصوصية',
    'pl': 'Informacja o prywatności',
    'fr': 'Avis de confidentialité',
    'es': 'Aviso de privacidad',
    'it': 'Informativa privacy',
  },
  'privacyNoticeBody': {
    'de':
        'Mit der Nutzung dieser App erklären Sie sich mit der Verarbeitung Ihrer personenbezogenen Daten einverstanden.\n\nStandortdaten:\n• Ihr Standort wird nur während der angemeldeten Arbeitszeit erfasst (nach Check-in), nicht dauerhaft und nicht privat.\n• Zweck: Sicherheit am Einsatzort und bessere Arbeitsabläufe / Produktion — nicht zur Dauerüberwachung.\n• Außerhalb der Arbeitszeit bzw. nach Check-out wird Ihr Standort nicht an den Arbeitgeber übermittelt.\n• Innerhalb der definierten Betriebsfläche kann die Position während der Schicht in Echtzeit aktualisiert werden, wenn Sie sich bewegen.\n\nWeitere Informationen: Profil → Rechtliches.',
    'en':
        'By using this app you agree to the processing of your personal data.\n\nLocation data:\n• Your location is only captured during your checked-in work time — not continuously and not in private life.\n• Purpose: on-site safety and better workflows / production — not constant surveillance.\n• Outside work time or after check-out your location is not sent to the employer.\n• Within the defined site area, position may update in real time while you move during the shift.\n\nMore details: Profile → Legal.',
    'tr':
        'Bu uygulamayı kullanarak kişisel verilerinizin işlenmesini kabul etmiş olursunuz.\n\nKonum verileri:\n• Konumunuz yalnızca giriş yaptığınız çalışma süresi boyunca kaydedilir — sürekli ve özel hayatta değil.\n• Amaç: sahada güvenlik ve daha iyi iş akışı / üretim — sürekli gözetim değil.\n• Çalışma dışı veya çıkış sonrası konum işverene gönderilmez.\n• Tanımlı saha içinde vardiya sırasında hareket ederseniz konum gerçek zamanlı güncellenebilir.\n\nAyrıntılar: Profil → Yasal.',
    'ar':
        'باستخدام هذا التطبيق فإنك توافق على معالجة بياناتك الشخصية.\n\nبيانات الموقع:\n• يُلتقط موقعك فقط أثناء وقت العمل بعد تسجيل الحضور — وليس بشكل دائم وليس في حياتك الخاصة.\n• الغرض: السلامة في موقع العمل وتحسين سير العمل/الإنتاج — وليس المراقبة المستمرة.\n• خارج وقت العمل أو بعد تسجيل المغادرة لا يُرسل موقعك لصاحب العمل.\n• داخل منطقة الموقع المحددة قد يُحدَّث الموقع لحظياً أثناء الوردية عند تحرّكك.\n\nالمزيد: الملف الشخصي → الشؤون القانونية.',
    'pl':
        'Korzystając z aplikacji zgadzasz się na przetwarzanie danych osobowych.\n\nDane lokalizacji:\n• Lokalizacja jest rejestrowana tylko w czasie pracy po zameldowaniu — nie stale i nie w życiu prywatnym.\n• Cel: bezpieczeństwo na budowie i lepsza organizacja / produkcja — nie ciągła inwigilacja.\n• Poza czasem pracy lub po wymeldowaniu lokalizacja nie jest wysyłana pracodawcy.\n• W wyznaczonym obszarze lokalizacja może być aktualizowana w czasie rzeczywistym podczas ruchu na zmianie.\n\nSzczegóły: Profil → Informacje prawne.',
    'fr':
        'En utilisant cette application, vous acceptez le traitement de vos données personnelles.\n\nDonnées de localisation :\n• Votre position n’est capturée que pendant le temps de travail après pointage — pas en continu ni dans la vie privée.\n• Objectif : sécurité sur site et meilleurs flux / production — pas une surveillance permanente.\n• Hors temps de travail ou après dépointage, la position n’est pas envoyée à l’employeur.\n• Dans la zone définie, la position peut être mise à jour en temps réel pendant le poste lorsque vous vous déplacez.\n\nPlus de détails : Profil → Mentions légales.',
    'es':
        'Al usar esta app acepta el tratamiento de sus datos personales.\n\nDatos de ubicación:\n• Su ubicación solo se captura durante el horario laboral tras el fichaje — no de forma continua ni en la vida privada.\n• Finalidad: seguridad en obra y mejores flujos / producción — no vigilancia permanente.\n• Fuera del horario o tras el check-out no se envía la ubicación al empleador.\n• Dentro del área definida, la posición puede actualizarse en tiempo real durante el turno al moverse.\n\nMás detalles: Perfil → Legal.',
    'it':
        'Utilizzando l’app accetti il trattamento dei tuoi dati personali.\n\nDati di posizione:\n• La posizione viene rilevata solo durante l’orario di lavoro dopo il check-in — non in continuo e non nella vita privata.\n• Scopo: sicurezza in cantiere e flussi / produzione migliori — non sorveglianza continua.\n• Fuori orario o dopo il check-out la posizione non viene inviata al datore di lavoro.\n• Nell’area definita la posizione può aggiornarsi in tempo reale durante il turno quando ti muovi.\n\nDettagli: Profilo → Legale.',
  },
  'privacyOpenLegal': {
    'de': 'Datenschutz & Impressum öffnen',
    'en': 'Open privacy & imprint',
    'tr': 'Gizlilik ve künye aç',
    'ar': 'فتح الخصوصية والبيانات القانونية',
    'pl': 'Otwórz prywatność i imprint',
    'fr': 'Ouvrir confidentialité & mentions',
    'es': 'Abrir privacidad e impresión',
    'it': 'Apri privacy e impronta',
  },
  'privacyDecline': {
    'de': 'Ablehnen',
    'en': 'Decline',
    'tr': 'Reddet',
    'ar': 'رفض',
    'pl': 'Odrzuć',
    'fr': 'Refuser',
    'es': 'Rechazar',
    'it': 'Rifiuta',
  },
  'privacyAccept': {
    'de': 'Verstanden & akzeptieren',
    'en': 'Understood & accept',
    'tr': 'Anladım ve kabul ediyorum',
    'ar': 'فهمت وأوافق',
    'pl': 'Rozumiem i akceptuję',
    'fr': 'Compris et j’accepte',
    'es': 'Entendido y acepto',
    'it': 'Ho capito e accetto',
  },
  'legalHubTitle': {
    'de': 'Rechtliches',
    'en': 'Legal',
    'tr': 'Yasal',
    'ar': 'الشؤون القانونية',
    'pl': 'Informacje prawne',
    'fr': 'Mentions légales',
    'es': 'Legal',
    'it': 'Legale',
  },
  'legalHubSectionTitle': {
    'de': 'Impressum & Datenschutz',
    'en': 'Imprint & privacy',
    'tr': 'Künye ve gizlilik',
    'ar': 'البيانات القانونية والخصوصية',
    'pl': 'Imprint i prywatność',
    'fr': 'Mentions & confidentialité',
    'es': 'Aviso legal y privacidad',
    'it': 'Impronta e privacy',
  },
  'legalHubIntro': {
    'de': 'Hier finden Sie die vom Arbeitgeber hinterlegten Angaben gemäß TMG/DDV und DSGVO (Art. 13).',
    'en': 'Here you find the texts provided by your employer under applicable imprint and privacy rules (GDPR Art. 13).',
    'tr': 'İşvereniniz tarafından saklanan künye ve gizlilik metinlerini burada bulursunuz (KVKK/GDPR Mad. 13).',
    'ar': 'هنا تجد النصوص التي أودعها صاحب العمل وفق قواعد النشر والخصوصية (المادة 13 من اللائحة العامة).',
    'pl': 'Tutaj znajdziesz treści pracodawcy zgodnie z wymogami imprintu i RODO (art. 13).',
    'fr': 'Vous trouverez ici les textes fournis par l’employeur (mentions légales et RGPD art. 13).',
    'es': 'Aquí están los textos del empleador según aviso legal y RGPD (art. 13).',
    'it': 'Qui trovi i testi del datore di lavoro (impronta e GDPR art. 13).',
  },
  'legalImprint': {
    'de': 'Impressum',
    'en': 'Imprint',
    'tr': 'Künye',
    'ar': 'البيانات القانونية',
    'pl': 'Imprint',
    'fr': 'Mentions légales',
    'es': 'Aviso legal',
    'it': 'Impronta',
  },
  'legalPrivacy': {
    'de': 'Datenschutz',
    'en': 'Privacy',
    'tr': 'Gizlilik',
    'ar': 'الخصوصية',
    'pl': 'Prywatność',
    'fr': 'Confidentialité',
    'es': 'Privacidad',
    'it': 'Privacy',
  },
  'legalImprintSubtitle': {
    'de': 'Anbieterkennzeichnung lesen',
    'en': 'Read provider information',
    'tr': 'Sağlayıcı bilgilerini oku',
    'ar': 'قراءة بيانات المزود',
    'pl': 'Przeczytaj dane dostawcy',
    'fr': 'Lire les informations éditeur',
    'es': 'Leer datos del proveedor',
    'it': 'Leggi dati del fornitore',
  },
  'legalImprintMissing': {
    'de': 'Noch kein Text hinterlegt',
    'en': 'No text stored yet',
    'tr': 'Henüz metin yok',
    'ar': 'لا يوجد نص بعد',
    'pl': 'Brak tekstu',
    'fr': 'Aucun texte pour l’instant',
    'es': 'Aún sin texto',
    'it': 'Nessun testo ancora',
  },
  'legalPrivacySubtitle': {
    'de': 'Datenschutzerklärung & Kontakt',
    'en': 'Privacy policy & contact',
    'tr': 'Gizlilik politikası ve iletişim',
    'ar': 'سياسة الخصوصية والتواصل',
    'pl': 'Polityka prywatności i kontakt',
    'fr': 'Politique de confidentialité & contact',
    'es': 'Política de privacidad y contacto',
    'it': 'Informativa privacy e contatti',
  },
  'legalPrivacyMissing': {
    'de': 'Erklärung fehlt — Kontakt unten',
    'en': 'Policy missing — contact below',
    'tr': 'Politika yok — iletişim aşağıda',
    'ar': 'السياسة غير متوفرة — التواصل أدناه',
    'pl': 'Brak polityki — kontakt poniżej',
    'fr': 'Politique absente — contact ci-dessous',
    'es': 'Falta la política — contacto abajo',
    'it': 'Informativa assente — contatti sotto',
  },
  'legalYourRights': {
    'de': 'Ihre Rechte (DSGVO)',
    'en': 'Your rights (GDPR)',
    'tr': 'Haklarınız (KVKK/GDPR)',
    'ar': 'حقوقك (اللائحة العامة)',
    'pl': 'Twoje prawa (RODO)',
    'fr': 'Vos droits (RGPD)',
    'es': 'Sus derechos (RGPD)',
    'it': 'I tuoi diritti (GDPR)',
  },
  'legalYourRightsHint': {
    'de': 'Art. 15 Auskunft · Art. 17 Löschung — Anfrage an Ihren Arbeitgeber.',
    'en': 'Art. 15 access · Art. 17 erasure — request to your employer.',
    'tr': 'Mad. 15 erişim · Mad. 17 silme — işvereninize talep.',
    'ar': 'المادة 15 اطلاع · المادة 17 محو — اطلب من صاحب العمل.',
    'pl': 'Art. 15 dostęp · Art. 17 usunięcie — wniosek do pracodawcy.',
    'fr': 'Art. 15 accès · Art. 17 effacement — demande à l’employeur.',
    'es': 'Art. 15 acceso · Art. 17 supresión — solicitud al empleador.',
    'it': 'Art. 15 accesso · Art. 17 cancellazione — richiesta al datore.',
  },
  'legalRequestAccess': {
    'de': 'Auskunft anfordern',
    'en': 'Request access',
    'tr': 'Erişim talep et',
    'ar': 'طلب الاطلاع',
    'pl': 'Poproś o dostęp',
    'fr': 'Demander un accès',
    'es': 'Solicitar acceso',
    'it': 'Richiedi accesso',
  },
  'legalRequestErasure': {
    'de': 'Löschung anfordern',
    'en': 'Request erasure',
    'tr': 'Silme talep et',
    'ar': 'طلب المحو',
    'pl': 'Poproś o usunięcie',
    'fr': 'Demander l’effacement',
    'es': 'Solicitar borrado',
    'it': 'Richiedi cancellazione',
  },
  'legalControllerTitle': {
    'de': 'Verantwortlicher (Arbeitgeber)',
    'en': 'Controller (employer)',
    'tr': 'Sorumlu (işveren)',
    'ar': 'المسؤول (صاحب العمل)',
    'pl': 'Administrator (pracodawca)',
    'fr': 'Responsable (employeur)',
    'es': 'Responsable (empleador)',
    'it': 'Titolare (datore di lavoro)',
  },
  'legalOperatorTitle': {
    'de': 'Plattform-Betreiber',
    'en': 'Platform operator',
    'tr': 'Platform işletmecisi',
    'ar': 'مشغّل المنصة',
    'pl': 'Operator platformy',
    'fr': 'Opérateur de la plateforme',
    'es': 'Operador de la plataforma',
    'it': 'Gestore della piattaforma',
  },
  'legalAccessSent': {
    'de': 'Auskunftsanfrage gesendet. Ihr Arbeitgeber bearbeitet sie.',
    'en': 'Access request sent. Your employer will process it.',
    'tr': 'Erişim talebi gönderildi. İşvereniniz işleyecek.',
    'ar': 'أُرسل طلب الاطلاع. سيعالجه صاحب العمل.',
    'pl': 'Wniosek o dostęp wysłany. Pracodawca go rozpatrzy.',
    'fr': 'Demande d’accès envoyée. Votre employeur la traitera.',
    'es': 'Solicitud de acceso enviada. Su empleador la tramitará.',
    'it': 'Richiesta di accesso inviata. Il datore la elaborerà.',
  },
  'legalErasureSent': {
    'de': 'Löschanfrage gesendet. Ihr Arbeitgeber bearbeitet sie.',
    'en': 'Erasure request sent. Your employer will process it.',
    'tr': 'Silme talebi gönderildi. İşvereniniz işleyecek.',
    'ar': 'أُرسل طلب المحو. سيعالجه صاحب العمل.',
    'pl': 'Wniosek o usunięcie wysłany. Pracodawca go rozpatrzy.',
    'fr': 'Demande d’effacement envoyée. Votre employeur la traitera.',
    'es': 'Solicitud de borrado enviada. Su empleador la tramitará.',
    'it': 'Richiesta di cancellazione inviata. Il datore la elaborerà.',
  },
  'legalLoadError': {
    'de': 'Rechtstexte konnten nicht geladen werden.',
    'en': 'Legal texts could not be loaded.',
    'tr': 'Yasal metinler yüklenemedi.',
    'ar': 'تعذّر تحميل النصوص القانونية.',
    'pl': 'Nie udało się wczytać tekstów prawnych.',
    'fr': 'Impossible de charger les textes légaux.',
    'es': 'No se pudieron cargar los textos legales.',
    'it': 'Impossibile caricare i testi legali.',
  },
  'legalControllerPrivacyTitle': {
    'de': 'Verantwortlicher für die Datenverarbeitung',
    'en': 'Controller for data processing',
    'tr': 'Veri işleme sorumlusu',
    'ar': 'المسؤول عن معالجة البيانات',
    'pl': 'Administrator przetwarzania danych',
    'fr': 'Responsable du traitement',
    'es': 'Responsable del tratamiento',
    'it': 'Titolare del trattamento',
  },
  'legalControllerPrivacyHint': {
    'de': 'Nach DSGVO Art. 13 müssen Sie den Verantwortlichen und dessen Kontaktdaten (insbesondere E-Mail) einsehen können.',
    'en': 'Under GDPR Art. 13 you must be able to see the controller and their contact details (especially email).',
    'tr': 'GDPR Mad. 13’e göre sorumluyu ve iletişim bilgilerini (özellikle e-posta) görebilmelisiniz.',
    'ar': 'بموجب المادة 13 يجب أن تستطيع رؤية المسؤول وبيانات الاتصال (خاصة البريد).',
    'pl': 'Zgodnie z art. 13 RODO musisz móc zobaczyć administratora i dane kontaktowe (zwłaszcza e-mail).',
    'fr': 'Selon le RGPD art. 13, vous devez pouvoir voir le responsable et ses coordonnées (surtout e-mail).',
    'es': 'Según el RGPD art. 13 debe poder ver al responsable y sus datos de contacto (especialmente el correo).',
    'it': 'Secondo GDPR art. 13 devi poter vedere il titolare e i contatti (soprattutto e-mail).',
  },
  'legalPrivacyEmpty': {
    'de': 'Es ist noch keine Datenschutzerklärung hinterlegt. Bitte wenden Sie sich an Ihren Arbeitgeber (Kontaktdaten oben) oder an den Plattform-Betreiber.',
    'en': 'No privacy policy is stored yet. Please contact your employer (details above) or the platform operator.',
    'tr': 'Henüz gizlilik politikası yok. İşvereninize (yukarıdaki iletişim) veya platform işletmecisine başvurun.',
    'ar': 'لا توجد سياسة خصوصية بعد. تواصل مع صاحب العمل (أعلاه) أو مشغّل المنصة.',
    'pl': 'Brak polityki prywatności. Skontaktuj się z pracodawcą (powyżej) lub operatorem platformy.',
    'fr': 'Aucune politique de confidentialité pour l’instant. Contactez votre employeur (ci-dessus) ou l’opérateur.',
    'es': 'Aún no hay política de privacidad. Contacte a su empleador (arriba) o al operador.',
    'it': 'Nessuna informativa privacy ancora. Contatta il datore (sopra) o il gestore della piattaforma.',
  },
  'legalImprintEmpty': {
    'de': 'Es ist noch kein Impressum hinterlegt. Sobald Ihr Arbeitgeber die Texte speichert, erscheinen sie hier.',
    'en': 'No imprint is stored yet. Once your employer saves the texts, they appear here.',
    'tr': 'Henüz künye yok. İşvereniniz metinleri kaydedince burada görünür.',
    'ar': 'لا توجد بيانات قانونية بعد. عند حفظ صاحب العمل للنصوص تظهر هنا.',
    'pl': 'Brak imprintu. Gdy pracodawca zapisze teksty, pojawią się tutaj.',
    'fr': 'Aucune mention légale pour l’instant. Elles apparaîtront ici une fois enregistrées.',
    'es': 'Aún no hay aviso legal. Aparecerá aquí cuando el empleador lo guarde.',
    'it': 'Nessuna impronta ancora. Comparirà qui quando il datore salva i testi.',
  },
  'legalOperatorAppTitle': {
    'de': 'Plattform-Betreiber (App-Anbieter)',
    'en': 'Platform operator (app provider)',
    'tr': 'Platform işletmecisi (uygulama sağlayıcı)',
    'ar': 'مشغّل المنصة (مزوّد التطبيق)',
    'pl': 'Operator platformy (dostawca aplikacji)',
    'fr': 'Opérateur de la plateforme (éditeur de l’app)',
    'es': 'Operador de la plataforma (proveedor de la app)',
    'it': 'Gestore della piattaforma (fornitore app)',
  },
  'shiftsSwapEmpty': {
    'de': 'Noch keine Tausch-Anfragen',
    'en': 'No swap requests yet',
    'tr': 'Henüz takas talebi yok',
    'ar': 'لا طلبات تبديل بعد',
    'pl': 'Brak próśb o zamianę',
    'fr': 'Aucune demande d’échange',
    'es': 'Aún no hay cambios',
    'it': 'Nessuna richiesta di scambio',
  },
  'shiftsSwapEmptyHint': {
    'de': 'Tippen Sie bei „Meine Schichten“ auf das Tausch-Symbol neben einer Schicht, um eine Anfrage zu stellen.',
    'en': 'On “My shifts”, tap the swap icon next to a shift to send a request.',
    'tr': '“Vardiyalarım”da bir vardiyanın yanındaki takas simgesine dokunarak talep gönderin.',
    'ar': 'في «وردياتي» اضغط أيقونة التبديل بجانب وردية لإرسال طلب.',
    'pl': 'W „Moje zmiany” stuknij ikonę zamiany obok zmiany, aby wysłać prośbę.',
    'fr': 'Dans « Mes équipes », touchez l’icône d’échange à côté d’une équipe pour envoyer une demande.',
    'es': 'En «Mis turnos», toque el icono de cambio junto a un turno para enviar una solicitud.',
    'it': 'In «I miei turni» tocca l’icona di scambio accanto a un turno per inviare una richiesta.',
  },
  'shiftsSwapTooltip': {
    'de': 'Abgeben / tauschen',
    'en': 'Hand off / swap',
    'tr': 'Devret / takas et',
    'ar': 'تسليم / تبديل',
    'pl': 'Oddaj / zamień',
    'fr': 'Céder / échanger',
    'es': 'Ceder / cambiar',
    'it': 'Cedi / scambia',
  },
  'shiftsNoneUpcoming': {
    'de': 'Keine anstehenden Schichten',
    'en': 'No upcoming shifts',
    'tr': 'Yaklaşan vardiya yok',
    'ar': 'لا ورديات قادمة',
    'pl': 'Brak nadchodzących zmian',
    'fr': 'Aucune équipe à venir',
    'es': 'Sin turnos próximos',
    'it': 'Nessun turno in arrivo',
  },
  'shiftsSwapSentGive': {
    'de': 'Tausch-Anfrage gesendet (Abgabe)',
    'en': 'Swap request sent (hand-off)',
    'tr': 'Takas talebi gönderildi (devretme)',
    'ar': 'أُرسل طلب التبديل (تسليم)',
    'pl': 'Wysłano prośbę o zamianę (oddanie)',
    'fr': 'Demande d’échange envoyée (cession)',
    'es': 'Solicitud de cambio enviada (cesión)',
    'it': 'Richiesta di scambio inviata (cessione)',
  },
  'shiftsSwapSentTrade': {
    'de': 'Tausch-Anfrage gesendet (Gegenschicht)',
    'en': 'Swap request sent (trade)',
    'tr': 'Takas talebi gönderildi (karşılıklı)',
    'ar': 'أُرسل طلب التبديل (مبادلة)',
    'pl': 'Wysłano prośbę o zamianę (wymiana)',
    'fr': 'Demande d’échange envoyée (contre-équipe)',
    'es': 'Solicitud de cambio enviada (intercambio)',
    'it': 'Richiesta di scambio inviata (scambio)',
  },
  'shiftsNoCoworkers': {
    'de': 'Keine Kollegen für Tausch verfügbar. Bitte später erneut laden oder Admin prüfen.',
    'en': 'No coworkers available for a swap. Reload later or ask an admin.',
    'tr': 'Takas için meslektaş yok. Daha sonra yenileyin veya yöneticiye sorun.',
    'ar': 'لا زملاء متاحين للتبديل. أعد التحميل لاحقاً أو اسأل المسؤول.',
    'pl': 'Brak kolegów do zamiany. Odśwież później lub zapytaj admina.',
    'fr': 'Aucun collègue disponible pour un échange. Rechargez plus tard ou demandez à un admin.',
    'es': 'No hay compañeros para cambiar. Recargue más tarde o consulte a un admin.',
    'it': 'Nessun collega disponibile per lo scambio. Ricarica più tardi o chiedi a un admin.',
  },
  'legalMailFailed': {
    'de': 'E-Mail an {email} konnte nicht geöffnet werden.',
    'en': 'Could not open email to {email}.',
    'tr': '{email} için e-posta açılamadı.',
    'ar': 'تعذّر فتح البريد إلى {email}.',
    'pl': 'Nie można otworzyć e-maila do {email}.',
    'fr': 'Impossible d’ouvrir l’e-mail vers {email}.',
    'es': 'No se pudo abrir el correo a {email}.',
    'it': 'Impossibile aprire l’e-mail a {email}.',
  },
  'legalCallFailed': {
    'de': 'Anruf an {phone} fehlgeschlagen.',
    'en': 'Call to {phone} failed.',
    'tr': '{phone} araması başarısız.',
    'ar': 'فشل الاتصال بـ {phone}.',
    'pl': 'Połączenie z {phone} nieudane.',
    'fr': 'Appel vers {phone} échoué.',
    'es': 'Falló la llamada a {phone}.',
    'it': 'Chiamata a {phone} non riuscita.',
  },
  'legalContact': {
    'de': 'Kontakt',
    'en': 'Contact',
    'tr': 'İletişim',
    'ar': 'تواصل',
    'pl': 'Kontakt',
    'fr': 'Contact',
    'es': 'Contacto',
    'it': 'Contatto',
  },
  'legalPublicEmpty': {
    'de': 'Noch kein Text hinterlegt. Nach dem Login finden Sie aktuelle Angaben unter Profil → Rechtliches.',
    'en': 'No text stored yet. After login you can find current details under Profile → Legal.',
    'tr': 'Henüz metin yok. Girişten sonra güncel bilgileri Profil → Yasal altında bulursunuz.',
    'ar': 'لا يوجد نص بعد. بعد تسجيل الدخول تجد التفاصيل الحالية ضمن الملف الشخصي → الشؤون القانونية.',
    'pl': 'Brak tekstu. Po zalogowaniu aktualne dane znajdziesz w Profil → Informacje prawne.',
    'fr': 'Aucun texte pour l’instant. Après connexion : Profil → Mentions légales.',
    'es': 'Aún sin texto. Tras iniciar sesión: Perfil → Legal.',
    'it': 'Nessun testo ancora. Dopo l’accesso: Profilo → Legale.',
  },
  'leaveNewRequest': {
    'de': 'Neuer Urlaubsantrag',
    'en': 'New leave request',
    'tr': 'Yeni izin talebi',
    'ar': 'طلب إجازة جديد',
    'pl': 'Nowy wniosek urlopowy',
    'fr': 'Nouvelle demande de congé',
    'es': 'Nueva solicitud de vacaciones',
    'it': 'Nuova richiesta di ferie',
  },
  'leavePlanDisabled': {
    'de': 'Urlaubsanträge sind in Ihrem Tarif nicht enthalten.',
    'en': 'Leave requests are not included in your company plan.',
    'tr': 'İzin talepleri paketinize dahil değil.',
    'ar': 'طلبات الإجازة غير مشمولة في خطتكم.',
    'pl': 'Wnioski urlopowe nie są w waszym planie.',
    'fr': 'Les congés ne sont pas inclus dans votre offre.',
    'es': 'Las vacaciones no están parte de su plan.',
    'it': 'Le ferie non sono incluse nel vostro piano.',
  },
  'leaveEmptyTitle': {
    'de': 'Noch keine Urlaubsanträge',
    'en': 'No leave requests yet',
    'tr': 'Henüz izin talebi yok',
    'ar': 'لا طلبات إجازة بعد',
    'pl': 'Brak wniosków urlopowych',
    'fr': 'Aucune demande de congé',
    'es': 'Aún no hay solicitudes',
    'it': 'Nessuna richiesta di ferie',
  },
  'leaveEmptyHint': {
    'de': 'Stelle einen Antrag — dein Team sieht ihn sofort im Admin-Portal von {brand}.',
    'en': 'Submit a request — your team sees it right away in the {brand} admin portal.',
    'tr': 'Talep oluşturun — ekibiniz hemen {brand} yönetici portalında görür.',
    'ar': 'قدّم طلباً — يراه فريقك فوراً في بوابة إدارة {brand}.',
    'pl': 'Złóż wniosek — zespół od razu zobaczy go w portalu {brand}.',
    'fr': 'Déposez une demande — votre équipe la voit aussitôt dans le portail {brand}.',
    'es': 'Envíe una solicitud: su equipo la verá de inmediato en el portal {brand}.',
    'it': 'Invia una richiesta: il team la vede subito nel portale {brand}.',
  },
  'leaveFirstRequest': {
    'de': 'Ersten Antrag stellen',
    'en': 'Create first request',
    'tr': 'İlk talebi oluştur',
    'ar': 'إنشاء أول طلب',
    'pl': 'Utwórz pierwszy wniosek',
    'fr': 'Créer la première demande',
    'es': 'Crear primera solicitud',
    'it': 'Crea la prima richiesta',
  },
  'leaveType': {
    'de': 'Art',
    'en': 'Type',
    'tr': 'Tür',
    'ar': 'النوع',
    'pl': 'Rodzaj',
    'fr': 'Type',
    'es': 'Tipo',
    'it': 'Tipo',
  },
  'leaveTypeVacation': {
    'de': 'Urlaub',
    'en': 'Vacation',
    'tr': 'İzin',
    'ar': 'إجازة',
    'pl': 'Urlop',
    'fr': 'Congés',
    'es': 'Vacaciones',
    'it': 'Ferie',
  },
  'leaveTypeSick': {
    'de': 'Krank',
    'en': 'Sick',
    'tr': 'Hastalık',
    'ar': 'مرض',
    'pl': 'Chorobowe',
    'fr': 'Maladie',
    'es': 'Baja',
    'it': 'Malattia',
  },
  'leaveTypeOther': {
    'de': 'Sonstiges',
    'en': 'Other',
    'tr': 'Diğer',
    'ar': 'أخرى',
    'pl': 'Inne',
    'fr': 'Autre',
    'es': 'Otro',
    'it': 'Altro',
  },
  'leaveStatusApproved': {
    'de': 'Genehmigt',
    'en': 'Approved',
    'tr': 'Onaylandı',
    'ar': 'موافق عليه',
    'pl': 'Zatwierdzony',
    'fr': 'Approuvé',
    'es': 'Aprobado',
    'it': 'Approvato',
  },
  'leaveStatusRejected': {
    'de': 'Abgelehnt',
    'en': 'Rejected',
    'tr': 'Reddedildi',
    'ar': 'مرفوض',
    'pl': 'Odrzucony',
    'fr': 'Refusé',
    'es': 'Rechazado',
    'it': 'Rifiutato',
  },
  'leaveStatusPending': {
    'de': 'Offen',
    'en': 'Pending',
    'tr': 'Beklemede',
    'ar': 'قيد الانتظار',
    'pl': 'Oczekujący',
    'fr': 'En attente',
    'es': 'Pendiente',
    'it': 'In attesa',
  },
  'leaveStartDate': {
    'de': 'Von',
    'en': 'Start date',
    'tr': 'Başlangıç',
    'ar': 'من',
    'pl': 'Od',
    'fr': 'Du',
    'es': 'Desde',
    'it': 'Dal',
  },
  'leaveEndDate': {
    'de': 'Bis',
    'en': 'End date',
    'tr': 'Bitiş',
    'ar': 'إلى',
    'pl': 'Do',
    'fr': 'Au',
    'es': 'Hasta',
    'it': 'Al',
  },
  'leaveNoteOptional': {
    'de': 'Notiz (optional)',
    'en': 'Note (optional)',
    'tr': 'Not (isteğe bağlı)',
    'ar': 'ملاحظة (اختياري)',
    'pl': 'Notatka (opcjonalnie)',
    'fr': 'Note (facultatif)',
    'es': 'Nota (opcional)',
    'it': 'Nota (opzionale)',
  },
  'leaveManagerEmailOptional': {
    'de': 'E-Mail Vorgesetzter (optional)',
    'en': 'Manager email (optional)',
    'tr': 'Yönetici e-postası (isteğe bağlı)',
    'ar': 'بريد المدير (اختياري)',
    'pl': 'E-mail przełożonego (opcjonalnie)',
    'fr': 'E-mail du responsable (facultatif)',
    'es': 'Correo del responsable (opcional)',
    'it': 'Email responsabile (opzionale)',
  },
  'leaveSubmit': {
    'de': 'Absenden',
    'en': 'Submit',
    'tr': 'Gönder',
    'ar': 'إرسال',
    'pl': 'Wyślij',
    'fr': 'Envoyer',
    'es': 'Enviar',
    'it': 'Invia',
  },
  'shiftsNoneUpcomingHint': {
    'de': 'Wenn Ihr Arbeitgeber den Einsatzplan nutzt, erscheinen Ihre Arbeitstage hier automatisch.',
    'en': 'If your employer uses the deployment plan, your work days appear here automatically.',
    'tr': 'İşvereniniz görev planını kullanıyorsa çalışma günleriniz burada otomatik görünür.',
    'ar': 'إذا استخدم صاحب العمل خطة النشر، تظهر أيام عملك هنا تلقائياً.',
    'pl': 'Jeśli pracodawca korzysta z planu rozmieszczenia, dni pracy pojawią się tu automatycznie.',
    'fr': 'Si votre employeur utilise le plan d’affectation, vos jours de travail apparaissent ici.',
    'es': 'Si su empresa usa el plan de despliegue, sus días de trabajo aparecen aquí.',
    'it': 'Se il datore usa il piano di impiego, i giorni di lavoro compaiono qui.',
  },
  'shiftsFromPlan': {
    'de': 'Aus Einsatzplan',
    'en': 'From deployment plan',
    'tr': 'Görev planından',
    'ar': 'من خطة النشر',
    'pl': 'Z planu rozmieszczenia',
    'fr': 'Du plan d’affectation',
    'es': 'Del plan de despliegue',
    'it': 'Dal piano di impiego',
  },
};
