import 'locale_controller.dart';

/// Compact in-app strings for native worker APK (DE/EN/TR/AR/PL/FR/ES/IT).
String t(String key, [String fallback = '']) {
  final lang = LocaleController.instance.lang;
  final row = _strings[key];
  if (row == null) return fallback.isNotEmpty ? fallback : key;
  return row[lang] ?? row['en'] ?? row['de'] ?? (fallback.isNotEmpty ? fallback : key);
}

const Map<String, Map<String, String>> _strings = {
  'navPass': {
    'de': 'Ausweis',
    'en': 'Pass',
    'tr': 'Kart',
    'ar': 'الهوية',
    'pl': 'Karta',
    'fr': 'Badge',
    'es': 'Pase',
    'it': 'Badge',
  },
  'navCheckin': {
    'de': 'Check-in',
    'en': 'Check-in',
    'tr': 'Giriş',
    'ar': 'تسجيل',
    'pl': 'Check-in',
    'fr': 'Pointage',
    'es': 'Entrada',
    'it': 'Check-in',
  },
  'navTasks': {
    'de': 'Aufgaben',
    'en': 'Tasks',
    'tr': 'Görevler',
    'ar': 'المهام',
    'pl': 'Zadania',
    'fr': 'Tâches',
    'es': 'Tareas',
    'it': 'Attività',
  },
  'navChat': {
    'de': 'Chat',
    'en': 'Chat',
    'tr': 'Sohbet',
    'ar': 'محادثة',
    'pl': 'Czat',
    'fr': 'Chat',
    'es': 'Chat',
    'it': 'Chat',
  },
  'navProfile': {
    'de': 'Profil',
    'en': 'Profile',
    'tr': 'Profil',
    'ar': 'الملف',
    'pl': 'Profil',
    'fr': 'Profil',
    'es': 'Perfil',
    'it': 'Profilo',
  },
  'language': {
    'de': 'Sprache',
    'en': 'Language',
    'tr': 'Dil',
    'ar': 'اللغة',
    'pl': 'Język',
    'fr': 'Langue',
    'es': 'Idioma',
    'it': 'Lingua',
  },
  'languageHint': {
    'de': 'Sprache jederzeit hier ändern.',
    'en': 'Change language anytime here.',
    'tr': 'Dili istediğiniz zaman buradan değiştirin.',
    'ar': 'غيّر اللغة في أي وقت من هنا.',
    'pl': 'Zmień język w dowolnym momencie.',
    'fr': 'Changez la langue ici à tout moment.',
    'es': 'Cambia el idioma aquí en cualquier momento.',
    'it': 'Cambia lingua qui in qualsiasi momento.',
  },
  'loginTitle': {
    'de': 'Digitalen Ausweis aktivieren',
    'en': 'Activate digital pass',
    'tr': 'Dijital kartı etkinleştir',
    'ar': 'تفعيل الهوية الرقمية',
    'pl': 'Aktywuj kartę cyfrową',
    'fr': 'Activer le badge numérique',
    'es': 'Activar pase digital',
    'it': 'Attiva badge digitale',
  },
  'loginSubtitle': {
    'de': 'Mitarbeiterausweis',
    'en': 'Employee pass',
    'tr': 'Personel kartı',
    'ar': 'بطاقة الموظف',
    'pl': 'Karta pracownika',
    'fr': 'Badge employé',
    'es': 'Pase de empleado',
    'it': 'Badge dipendente',
  },
  'loginManual': {
    'de': 'Manuell',
    'en': 'Manual',
    'tr': 'Manuel',
    'ar': 'يدوي',
    'pl': 'Ręcznie',
    'fr': 'Manuel',
    'es': 'Manual',
    'it': 'Manuale',
  },
  'loginQr': {
    'de': 'QR-Scan',
    'en': 'QR scan',
    'tr': 'QR tara',
    'ar': 'مسح QR',
    'pl': 'Skan QR',
    'fr': 'Scan QR',
    'es': 'Escanear QR',
    'it': 'Scansiona QR',
  },
  'loginManualTitle': {
    'de': 'Manuelle Anmeldung',
    'en': 'Manual sign-in',
    'tr': 'Manuel giriş',
    'ar': 'تسجيل الدخول اليدوي',
    'pl': 'Logowanie ręczne',
    'fr': 'Connexion manuelle',
    'es': 'Inicio manual',
    'it': 'Accesso manuale',
  },
  'loginManualHint': {
    'de': 'Badge-ID + PIN vom Admin, oder den kompletten Join-Link einfügen.',
    'en': 'Enter Badge-ID + PIN from admin, or paste the full join link.',
    'tr': 'Yöneticiden Badge-ID + PIN girin veya join bağlantısını yapıştırın.',
    'ar': 'أدخل رقم الشارة ورمز PIN من المسؤول، أو الصق رابط التفعيل كاملاً.',
    'pl': 'Wpisz Badge-ID + PIN od admina albo wklej pełny link join.',
    'fr': 'Saisissez Badge-ID + PIN, ou collez le lien d’activation.',
    'es': 'Introduce Badge-ID + PIN, o pega el enlace de activación.',
    'it': 'Inserisci Badge-ID + PIN, oppure incolla il link di attivazione.',
  },
  'loginBadge': {
    'de': 'Badge-ID',
    'en': 'Badge ID',
    'tr': 'Kart ID',
    'ar': 'رقم الشارة',
    'pl': 'ID karty',
    'fr': 'ID badge',
    'es': 'ID de pase',
    'it': 'ID badge',
  },
  'loginPin': {
    'de': 'PIN',
    'en': 'PIN',
    'tr': 'PIN',
    'ar': 'رمز PIN',
    'pl': 'PIN',
    'fr': 'PIN',
    'es': 'PIN',
    'it': 'PIN',
  },
  'loginLink': {
    'de': 'Einmal-Aktivierungslink (optional)',
    'en': 'One-time activation link (optional)',
    'tr': 'Tek kullanımlık link (opsiyonel)',
    'ar': 'رابط التفعيل لمرة واحدة (اختياري)',
    'pl': 'Link aktywacyjny (opcjonalnie)',
    'fr': 'Lien d’activation (optionnel)',
    'es': 'Enlace de activación (opcional)',
    'it': 'Link di attivazione (opzionale)',
  },
  'loginSubmit': {
    'de': 'Anmelden',
    'en': 'Sign in',
    'tr': 'Giriş yap',
    'ar': 'تسجيل الدخول',
    'pl': 'Zaloguj',
    'fr': 'Se connecter',
    'es': 'Iniciar sesión',
    'it': 'Accedi',
  },
  'loginQrTitle': {
    'de': 'Aktivierungs-QR scannen',
    'en': 'Scan activation QR',
    'tr': 'Aktivasyon QR tara',
    'ar': 'امسح رمز التفعيل',
    'pl': 'Zeskanuj QR aktywacji',
    'fr': 'Scanner le QR d’activation',
    'es': 'Escanear QR de activación',
    'it': 'Scansiona QR di attivazione',
  },
  'loginQrHint': {
    'de': 'Kamera erlauben, dann Admin-QR scannen.',
    'en': 'Allow camera, then scan the admin QR.',
    'tr': 'Kameraya izin verin, ardından yönetici QR’sını tarayın.',
    'ar': 'اسمح بالكاميرا ثم امسح رمز المسؤول.',
    'pl': 'Zezwól na kamerę, potem zeskanuj QR admina.',
    'fr': 'Autorisez la caméra, puis scannez le QR admin.',
    'es': 'Permite la cámara y escanea el QR del admin.',
    'it': 'Consenti la fotocamera e scansiona il QR admin.',
  },
  'legal': {
    'de': 'Rechtliches',
    'en': 'Legal',
    'tr': 'Yasal',
    'ar': 'قانوني',
    'pl': 'Informacje prawne',
    'fr': 'Mentions légales',
    'es': 'Legal',
    'it': 'Note legali',
  },
  'privacy': {
    'de': 'Datenschutz',
    'en': 'Privacy',
    'tr': 'Gizlilik',
    'ar': 'الخصوصية',
    'pl': 'Prywatność',
    'fr': 'Confidentialité',
    'es': 'Privacidad',
    'it': 'Privacy',
  },
  'imprint': {
    'de': 'Impressum',
    'en': 'Imprint',
    'tr': 'Künye',
    'ar': 'بيانات الناشر',
    'pl': 'Impressum',
    'fr': 'Mentions',
    'es': 'Aviso legal',
    'it': 'Note legali',
  },
  'cardEmployee': {
    'de': 'MITARBEITERAUSWEIS',
    'en': 'EMPLOYEE PASS',
    'tr': 'PERSONEL KARTI',
    'ar': 'بطاقة الموظف',
    'pl': 'KARTA PRACOWNIKA',
    'fr': 'BADGE EMPLOYÉ',
    'es': 'PASE DE EMPLEADO',
    'it': 'BADGE DIPENDENTE',
  },
  'attachFailed': {
    'de': 'Anhang senden fehlgeschlagen',
    'en': 'Failed to send attachment',
    'tr': 'Ek gönderilemedi',
    'ar': 'فشل إرسال المرفق',
    'pl': 'Nie udało się wysłać załącznika',
    'fr': 'Échec de l’envoi de la pièce jointe',
    'es': 'No se pudo enviar el adjunto',
    'it': 'Invio allegato non riuscito',
  },
  'shiftSwap': {
    'de': 'Schicht tauschen',
    'en': 'Swap shift',
    'tr': 'Vardiya değiştir',
    'ar': 'تبديل الوردية',
    'pl': 'Zamień zmianę',
    'fr': 'Échanger le quart',
    'es': 'Cambiar turno',
    'it': 'Scambia turno',
  },
  'shiftsMine': {
    'de': 'Meine Schichten',
    'en': 'My shifts',
    'tr': 'Vardiyalarım',
    'ar': 'وردياتي',
    'pl': 'Moje zmiany',
    'fr': 'Mes quarts',
    'es': 'Mis turnos',
    'it': 'I miei turni',
  },
  'shiftsSwapTab': {
    'de': 'Tausch',
    'en': 'Swap',
    'tr': 'Değişim',
    'ar': 'تبديل',
    'pl': 'Zamiana',
    'fr': 'Échange',
    'es': 'Cambio',
    'it': 'Scambio',
  },
  'logout': {
    'de': 'Abmelden',
    'en': 'Sign out',
    'tr': 'Çıkış',
    'ar': 'تسجيل الخروج',
    'pl': 'Wyloguj',
    'fr': 'Déconnexion',
    'es': 'Cerrar sesión',
    'it': 'Esci',
  },
  'badge': {
    'de': 'Badge',
    'en': 'Badge',
    'tr': 'Kart',
    'ar': 'الشارة',
    'pl': 'Identyfikator',
    'fr': 'Badge',
    'es': 'Pase',
    'it': 'Badge',
  },
  'role': {
    'de': 'Rolle',
    'en': 'Role',
    'tr': 'Rol',
    'ar': 'الدور',
    'pl': 'Rola',
    'fr': 'Rôle',
    'es': 'Rol',
    'it': 'Ruolo',
  },
  'site': {
    'de': 'Standort',
    'en': 'Site',
    'tr': 'Şantiye',
    'ar': 'الموقع',
    'pl': 'Lokalizacja',
    'fr': 'Chantier',
    'es': 'Obra',
    'it': 'Cantiere',
  },
  'leave': {
    'de': 'Urlaub',
    'en': 'Leave',
    'tr': 'İzin',
    'ar': 'الإجازة',
    'pl': 'Urlop',
    'fr': 'Congés',
    'es': 'Vacaciones',
    'it': 'Ferie',
  },
  'leaveRemaining': {
    'de': 'Verbleibend',
    'en': 'Remaining',
    'tr': 'Kalan',
    'ar': 'المتبقي',
    'pl': 'Pozostało',
    'fr': 'Restant',
    'es': 'Restante',
    'it': 'Rimanenti',
  },
  'leaveTaken': {
    'de': 'Genommen (Jahr)',
    'en': 'Taken (year)',
    'tr': 'Kullanılan (yıl)',
    'ar': 'المستخدم (سنة)',
    'pl': 'Wykorzystane (rok)',
    'fr': 'Pris (année)',
    'es': 'Tomados (año)',
    'it': 'Usati (anno)',
  },
  'days': {
    'de': 'Tage',
    'en': 'days',
    'tr': 'gün',
    'ar': 'أيام',
    'pl': 'dni',
    'fr': 'jours',
    'es': 'días',
    'it': 'giorni',
  },
  'teamOnSite': {
    'de': 'Team vor Ort',
    'en': 'Team on site',
    'tr': 'Sahadaki ekip',
    'ar': 'الفريق في الموقع',
    'pl': 'Zespół na miejscu',
    'fr': 'Équipe sur place',
    'es': 'Equipo en obra',
    'it': 'Squadra in cantiere',
  },
  'present': {
    'de': 'Anwesend',
    'en': 'Present',
    'tr': 'Mevcut',
    'ar': 'الحاضرون',
    'pl': 'Obecni',
    'fr': 'Présents',
    'es': 'Presentes',
    'it': 'Presenti',
  },
  'appUpdates': {
    'de': 'App-Updates',
    'en': 'App updates',
    'tr': 'Uygulama güncellemeleri',
    'ar': 'تحديثات التطبيق',
    'pl': 'Aktualizacje aplikacji',
    'fr': 'Mises à jour',
    'es': 'Actualizaciones',
    'it': 'Aggiornamenti app',
  },
  'pushNotifications': {
    'de': 'Push-Benachrichtigungen',
    'en': 'Push notifications',
    'tr': 'Anlık bildirimler',
    'ar': 'إشعارات الدفع',
    'pl': 'Powiadomienia push',
    'fr': 'Notifications push',
    'es': 'Notificaciones push',
    'it': 'Notifiche push',
  },
  'legalSubtitle': {
    'de': 'Impressum & Datenschutz',
    'en': 'Imprint & privacy',
    'tr': 'Künye ve gizlilik',
    'ar': 'بيانات الناشر والخصوصية',
    'pl': 'Impressum i prywatność',
    'fr': 'Mentions & confidentialité',
    'es': 'Aviso legal y privacidad',
    'it': 'Note legali e privacy',
  },
  'privacySubtitle': {
    'de': 'Erklärung & Firmenkontakt',
    'en': 'Policy & company contact',
    'tr': 'Açıklama ve şirket iletişimi',
    'ar': 'السياسة وتواصل الشركة',
    'pl': 'Polityka i kontakt firmy',
    'fr': 'Politique et contact',
    'es': 'Política y contacto',
    'it': 'Informativa e contatti',
  },
  'checkedInToday': {
    'de': 'Heute eingecheckt',
    'en': 'Checked in today',
    'tr': 'Bugün giriş yapıldı',
    'ar': 'تم التسجيل اليوم',
    'pl': 'Zameldowano dziś',
    'fr': 'Pointé aujourd’hui',
    'es': 'Registrado hoy',
    'it': 'Check-in oggi',
  },
  'notCheckedIn': {
    'de': 'Noch nicht eingecheckt',
    'en': 'Not checked in yet',
    'tr': 'Henüz giriş yapılmadı',
    'ar': 'لم يتم التسجيل بعد',
    'pl': 'Jeszcze nie zameldowano',
    'fr': 'Pas encore pointé',
    'es': 'Aún no registrado',
    'it': 'Non ancora in check-in',
  },
  'constructionSite': {
    'de': 'Baustelle',
    'en': 'Site',
    'tr': 'Şantiye',
    'ar': 'موقع البناء',
    'pl': 'Budowa',
    'fr': 'Chantier',
    'es': 'Obra',
    'it': 'Cantiere',
  },
  'nfcCheckin': {
    'de': 'NFC Check-in / Check-out',
    'en': 'NFC check-in / check-out',
    'tr': 'NFC giriş / çıkış',
    'ar': 'تسجيل الدخول/الخروج بـ NFC',
    'pl': 'NFC check-in / check-out',
    'fr': 'Pointage NFC',
    'es': 'Check-in / out NFC',
    'it': 'Check-in / out NFC',
  },
  'myDeploymentPlan': {
    'de': 'Mein Einsatzplan',
    'en': 'My schedule',
    'tr': 'Görev planım',
    'ar': 'خطة عملي',
    'pl': 'Mój plan pracy',
    'fr': 'Mon planning',
    'es': 'Mi plan',
    'it': 'Il mio piano',
  },
  'walletHint': {
    'de': 'Wallet fürs Gate · QR bleibt Fallback',
    'en': 'Wallet for the gate · QR remains fallback',
    'tr': 'Kapı için cüzdan · QR yedek kalır',
    'ar': 'المحفظة للبوابة · رمز QR كاحتياط',
    'pl': 'Portfel do bramy · QR jako zapas',
    'fr': 'Wallet pour le portail · QR en secours',
    'es': 'Wallet para el acceso · QR de respaldo',
    'it': 'Wallet per il gate · QR di riserva',
  },
  'morningBriefTitle': {
    'de': 'Morgenüberblick',
    'en': 'Morning overview',
    'tr': 'Sabah özeti',
    'ar': 'نظرة الصباح',
    'pl': 'Poranny przegląd',
    'fr': 'Aperçu du matin',
    'es': 'Resumen matutino',
    'it': 'Panoramica mattutina',
  },
  'morningCheckedIn': {
    'de': 'Eingecheckt',
    'en': 'Checked in',
    'tr': 'Giriş yapıldı',
    'ar': 'تم التسجيل',
    'pl': 'Zameldowano',
    'fr': 'Pointé',
    'es': 'Registrado',
    'it': 'In check-in',
  },
  'morningNotCheckedIn': {
    'de': 'Noch nicht eingecheckt',
    'en': 'Not checked in yet',
    'tr': 'Henüz giriş yok',
    'ar': 'لم يتم التسجيل بعد',
    'pl': 'Brak zameldowania',
    'fr': 'Pas encore pointé',
    'es': 'Aún sin registro',
    'it': 'Non ancora in check-in',
  },
  'morningColleagues': {
    'de': '{n} Kollegen vor Ort',
    'en': '{n} colleagues on site',
    'tr': '{n} meslektaş sahada',
    'ar': '{n} زملاء في الموقع',
    'pl': '{n} kolegów na budowie',
    'fr': '{n} collègues sur site',
    'es': '{n} colegas en obra',
    'it': '{n} colleghi in cantiere',
  },
  'morningChat': {
    'de': '{n} Chat ungelesen',
    'en': '{n} unread chat',
    'tr': '{n} okunmamış sohbet',
    'ar': '{n} محادثة غير مقروءة',
    'pl': '{n} nieprzeczytanych czatów',
    'fr': '{n} chat non lus',
    'es': '{n} chats sin leer',
    'it': '{n} chat non lette',
  },
  'morningLeave': {
    'de': '{n} Urlaub offen',
    'en': '{n} leave pending',
    'tr': '{n} izin bekliyor',
    'ar': '{n} إجازة معلّقة',
    'pl': '{n} urlop oczekuje',
    'fr': '{n} congés en attente',
    'es': '{n} vacaciones pendientes',
    'it': '{n} ferie in attesa',
  },
  'morningDocs': {
    'de': '{n} Docs laufen ab',
    'en': '{n} docs expiring',
    'tr': '{n} belge süresi doluyor',
    'ar': '{n} مستندات تنتهي',
    'pl': '{n} docs wygasają',
    'fr': '{n} docs expirent',
    'es': '{n} docs caducan',
    'it': '{n} docs in scadenza',
  },
  'morningGoCheckin': {
    'de': 'Check-in',
    'en': 'Check-in',
    'tr': 'Giriş',
    'ar': 'تسجيل',
    'pl': 'Check-in',
    'fr': 'Pointage',
    'es': 'Entrada',
    'it': 'Check-in',
  },
  'morningGoChat': {
    'de': 'Chat',
    'en': 'Chat',
    'tr': 'Sohbet',
    'ar': 'محادثة',
    'pl': 'Czat',
    'fr': 'Chat',
    'es': 'Chat',
    'it': 'Chat',
  },
  'morningGoDocs': {
    'de': 'Docs / Aufgaben',
    'en': 'Docs / tasks',
    'tr': 'Belgeler / görevler',
    'ar': 'مستندات / مهام',
    'pl': 'Docs / zadania',
    'fr': 'Docs / tâches',
    'es': 'Docs / tareas',
    'it': 'Docs / compiti',
  },
  'toAppleWallet': {
    'de': 'Zu Apple Wallet',
    'en': 'Add to Apple Wallet',
    'tr': 'Apple Wallet’a ekle',
    'ar': 'إضافة إلى Apple Wallet',
    'pl': 'Dodaj do Apple Wallet',
    'fr': 'Ajouter à Apple Wallet',
    'es': 'Añadir a Apple Wallet',
    'it': 'Aggiungi ad Apple Wallet',
  },
  'toGoogleWallet': {
    'de': 'Zu Google Wallet',
    'en': 'Add to Google Wallet',
    'tr': 'Google Wallet’a ekle',
    'ar': 'إضافة إلى Google Wallet',
    'pl': 'Dodaj do Google Wallet',
    'fr': 'Ajouter à Google Wallet',
    'es': 'Añadir a Google Wallet',
    'it': 'Aggiungi a Google Wallet',
  },
  'profileLoadError': {
    'de': 'Profil konnte nicht geladen werden — nach unten ziehen zum Aktualisieren.',
    'en': 'Could not load profile — pull down to refresh.',
    'tr': 'Profil yüklenemedi — yenilemek için aşağı çekin.',
    'ar': 'تعذّر تحميل الملف — اسحب للأسفل للتحديث.',
    'pl': 'Nie udało się wczytać profilu — przeciągnij w dół.',
    'fr': 'Profil introuvable — tirez pour actualiser.',
    'es': 'No se pudo cargar el perfil — desliza para actualizar.',
    'it': 'Profilo non caricato — scorri per aggiornare.',
  },
  'cardActive': {
    'de': 'AKTIV',
    'en': 'ACTIVE',
    'tr': 'AKTİF',
    'ar': 'نشط',
    'pl': 'AKTYWNY',
    'fr': 'ACTIF',
    'es': 'ACTIVO',
    'it': 'ATTIVO',
  },
  'cardBadgeId': {
    'de': 'BADGE-ID',
    'en': 'BADGE ID',
    'tr': 'KART ID',
    'ar': 'رقم الشارة',
    'pl': 'ID KARTY',
    'fr': 'ID BADGE',
    'es': 'ID PASE',
    'it': 'ID BADGE',
  },
  'cardValidUntil': {
    'de': 'GÜLTIG BIS',
    'en': 'VALID UNTIL',
    'tr': 'GEÇERLİLİK',
    'ar': 'صالح حتى',
    'pl': 'WAŻNY DO',
    'fr': 'VALABLE JUSQU’AU',
    'es': 'VÁLIDO HASTA',
    'it': 'VALIDO FINO',
  },
  'cardEmployeeName': {
    'de': 'Mitarbeiter',
    'en': 'Employee',
    'tr': 'Çalışan',
    'ar': 'الموظف',
    'pl': 'Pracownik',
    'fr': 'Employé',
    'es': 'Empleado',
    'it': 'Dipendente',
  },
  'notifications': {
    'de': 'Mitteilungen',
    'en': 'Notifications',
    'tr': 'Bildirimler',
    'ar': 'الإشعارات',
    'pl': 'Powiadomienia',
    'fr': 'Notifications',
    'es': 'Notificaciones',
    'it': 'Notifiche',
  },
  'callEmployer': {
    'de': 'Firma anrufen',
    'en': 'Call company',
    'tr': 'Firmayı ara',
    'ar': 'اتصل بالشركة',
    'pl': 'Zadzwoń do firmy',
    'fr': 'Appeler l’entreprise',
    'es': 'Llamar a la empresa',
    'it': 'Chiama l’azienda',
  },
  'contacts': {
    'de': 'Kontakte',
    'en': 'Contacts',
    'tr': 'Kişiler',
    'ar': 'جهات الاتصال',
    'pl': 'Kontakty',
    'fr': 'Contacts',
    'es': 'Contactos',
    'it': 'Contatti',
  },
  'employer': {
    'de': 'Arbeitgeber',
    'en': 'Employer',
    'tr': 'İşveren',
    'ar': 'صاحب العمل',
    'pl': 'Pracodawca',
    'fr': 'Employeur',
    'es': 'Empleador',
    'it': 'Datore',
  },
  'chatShowOriginal': {
    'de': 'Original anzeigen',
    'en': 'Show original',
    'tr': 'Orijinali göster',
    'ar': 'إظهار النص الأصلي',
    'pl': 'Pokaż oryginał',
    'fr': 'Afficher l’original',
    'es': 'Mostrar original',
    'it': 'Mostra originale',
  },
  'chatShowTranslation': {
    'de': 'Übersetzung anzeigen',
    'en': 'Show translation',
    'tr': 'Çeviriyi göster',
    'ar': 'إظهار الترجمة',
    'pl': 'Pokaż tłumaczenie',
    'fr': 'Afficher la traduction',
    'es': 'Mostrar traducción',
    'it': 'Mostra traduzione',
  },
  'chatTranslated': {
    'de': 'Übersetzt',
    'en': 'Translated',
    'tr': 'Çevrildi',
    'ar': 'مترجم',
    'pl': 'Przetłumaczono',
    'fr': 'Traduit',
    'es': 'Traducido',
    'it': 'Tradotto',
  },
  'chatReply': {
    'de': 'Antworten',
    'en': 'Reply',
    'tr': 'Yanıtla',
    'ar': 'رد',
    'pl': 'Odpowiedz',
    'fr': 'Répondre',
    'es': 'Responder',
    'it': 'Rispondi',
  },
  'chatCopy': {
    'de': 'Kopieren',
    'en': 'Copy',
    'tr': 'Kopyala',
    'ar': 'نسخ',
    'pl': 'Kopiuj',
    'fr': 'Copier',
    'es': 'Copiar',
    'it': 'Copia',
  },
  'chatCopied': {
    'de': 'Kopiert',
    'en': 'Copied',
    'tr': 'Kopyalandı',
    'ar': 'تم النسخ',
    'pl': 'Skopiowano',
    'fr': 'Copié',
    'es': 'Copiado',
    'it': 'Copiato',
  },
  'chatPin': {
    'de': 'Anheften',
    'en': 'Pin',
    'tr': 'Sabitle',
    'ar': 'تثبيت',
    'pl': 'Przypnij',
    'fr': 'Épingler',
    'es': 'Fijar',
    'it': 'Fissa',
  },
  'chatUnpin': {
    'de': 'Loslösen',
    'en': 'Unpin',
    'tr': 'Kaldır',
    'ar': 'إلغاء التثبيت',
    'pl': 'Odepnij',
    'fr': 'Désépingler',
    'es': 'Desfijar',
    'it': 'Sblocca',
  },
  'chatStar': {
    'de': 'Mit Stern markieren',
    'en': 'Star',
    'tr': 'Yıldızla',
    'ar': 'تمييز بنجمة',
    'pl': 'Oznacz gwiazdką',
    'fr': 'Favori',
    'es': 'Destacar',
    'it': 'Preferito',
  },
  'chatUnstar': {
    'de': 'Stern entfernen',
    'en': 'Remove star',
    'tr': 'Yıldızı kaldır',
    'ar': 'إزالة النجمة',
    'pl': 'Usuń gwiazdkę',
    'fr': 'Retirer le favori',
    'es': 'Quitar destacado',
    'it': 'Rimuovi preferito',
  },
  'chatDelete': {
    'de': 'Löschen',
    'en': 'Delete',
    'tr': 'Sil',
    'ar': 'حذف',
    'pl': 'Usuń',
    'fr': 'Supprimer',
    'es': 'Eliminar',
    'it': 'Elimina',
  },
  'chatDeleteFailed': {
    'de': 'Löschen fehlgeschlagen',
    'en': 'Delete failed',
    'tr': 'Silinemedi',
    'ar': 'فشل الحذف',
    'pl': 'Usuwanie nieudane',
    'fr': 'Échec de suppression',
    'es': 'Error al eliminar',
    'it': 'Eliminazione non riuscita',
  },
  'splashTagline': {
    'de': 'Mitarbeiter-App',
    'en': 'Employee app',
    'tr': 'Personel uygulaması',
    'ar': 'تطبيق الموظف',
    'pl': 'Aplikacja pracownika',
    'fr': 'App employé',
    'es': 'App de empleado',
    'it': 'App dipendente',
  },
  'helloName': {
    'de': 'Hallo, {name}',
    'en': 'Hello, {name}',
    'tr': 'Merhaba, {name}',
    'ar': 'مرحباً، {name}',
    'pl': 'Cześć, {name}',
    'fr': 'Bonjour, {name}',
    'es': 'Hola, {name}',
    'it': 'Ciao, {name}',
  },
  'todayHours': {
    'de': 'Heute: {h}',
    'en': 'Today: {h}',
    'tr': 'Bugün: {h}',
    'ar': 'اليوم: {h}',
    'pl': 'Dziś: {h}',
    'fr': "Aujourd'hui : {h}",
    'es': 'Hoy: {h}',
    'it': 'Oggi: {h}',
  },
  'todayHoursOpen': {
    'de': 'Heute: {h} (eingestempelt)',
    'en': 'Today: {h} (clocked in)',
    'tr': 'Bugün: {h} (giriş yapılmış)',
    'ar': 'اليوم: {h} (مسجّل دخول)',
    'pl': 'Dziś: {h} (zalogowany)',
    'fr': "Aujourd'hui : {h} (pointé)",
    'es': 'Hoy: {h} (fichado)',
    'it': 'Oggi: {h} (in ingresso)',
  },
  'openTimesheet': {
    'de': 'Stundennachweis öffnen',
    'en': 'Open timesheet',
    'tr': 'Puantajı aç',
    'ar': 'فتح سجل الساعات',
    'pl': 'Otwórz ewidencję',
    'fr': 'Ouvrir le relevé',
    'es': 'Abrir parte de horas',
    'it': 'Apri foglio ore',
  },
  'gpsNoNfcTitle': {
    'de': 'GPS ohne NFC',
    'en': 'GPS without NFC',
    'tr': 'NFC olmadan GPS',
    'ar': 'GPS بدون NFC',
    'pl': 'GPS bez NFC',
    'fr': 'GPS sans NFC',
    'es': 'GPS sin NFC',
    'it': 'GPS senza NFC',
  },
  'gpsNoNfcHint': {
    'de': 'Ein- oder ausstempeln auf der Baustelle (ohne NFC-Karte).',
    'en': 'Clock in or out on site (without NFC card).',
    'tr': 'Sahada giriş/çıkış (NFC kartı olmadan).',
    'ar': 'تسجيل الدخول أو الخروج في الموقع (بدون بطاقة NFC).',
    'pl': 'Wejście/wyjście na budowie (bez karty NFC).',
    'fr': 'Pointer sur le chantier (sans carte NFC).',
    'es': 'Fichar en obra (sin tarjeta NFC).',
    'it': 'Timbratura in cantiere (senza carta NFC).',
  },
  'gpsCheckinAuto': {
    'de': 'GPS — Anmelden / Abmelden',
    'en': 'GPS — Check in / out',
    'tr': 'GPS — Giriş / çıkış',
    'ar': 'GPS — تسجيل دخول / خروج',
    'pl': 'GPS — Wejście / wyjście',
    'fr': 'GPS — Entrée / sortie',
    'es': 'GPS — Entrada / salida',
    'it': 'GPS — Entrata / uscita',
  },
  'gpsIn': {
    'de': 'Ein',
    'en': 'In',
    'tr': 'Giriş',
    'ar': 'دخول',
    'pl': 'Wejście',
    'fr': 'Entrée',
    'es': 'Entrada',
    'it': 'Entrata',
  },
  'gpsOut': {
    'de': 'Aus',
    'en': 'Out',
    'tr': 'Çıkış',
    'ar': 'خروج',
    'pl': 'Wyjście',
    'fr': 'Sortie',
    'es': 'Salida',
    'it': 'Uscita',
  },
  'nfcGateTitle': {
    'de': 'NFC am Bauzaun',
    'en': 'NFC at the gate',
    'tr': 'Kapıda NFC',
    'ar': 'NFC عند البوابة',
    'pl': 'NFC przy bramie',
    'fr': 'NFC au portail',
    'es': 'NFC en el acceso',
    'it': 'NFC al cancello',
  },
  'nfcGateHint': {
    'de': '1. Physische Karte am Gate-Reader (empfohlen bei schlechtem Netz).\n2. Oder NFC hier scannen — offline zwischengespeichert, später synchronisiert.',
    'en': '1. Physical card at the gate reader (recommended on poor network).\n2. Or scan NFC here — stored offline, synced later.',
    'tr': '1. Kapı okuyucuda fiziksel kart (zayıf ağda önerilir).\n2. Veya burada NFC tarayın — çevrimdışı kaydedilir, sonra senkronize edilir.',
    'ar': '1. البطاقة الفعلية عند قارئ البوابة (موصى به عند ضعف الشبكة).\n2. أو امسح NFC هنا — يُحفظ دون اتصال ويُزامن لاحقاً.',
    'pl': '1. Fizyczna karta przy czytniku (zalecane przy słabej sieci).\n2. Lub zeskanuj NFC tutaj — zapis offline, synchronizacja później.',
    'fr': '1. Carte physique au lecteur (recommandé si réseau faible).\n2. Ou scannez le NFC ici — stocké hors ligne, synchronisé plus tard.',
    'es': '1. Tarjeta física en el lector (recomendado con mala red).\n2. O escanea NFC aquí — se guarda sin conexión y se sincroniza después.',
    'it': '1. Carta fisica al lettore (consigliato con rete scarsa).\n2. Oppure scansiona NFC qui — salvato offline, sincronizzato dopo.',
  },
  'badgeIdLabel': {
    'de': 'Badge-ID: {id}',
    'en': 'Badge ID: {id}',
    'tr': 'Kart ID: {id}',
    'ar': 'معرّف الشارة: {id}',
    'pl': 'ID karty: {id}',
    'fr': 'ID badge : {id}',
    'es': 'ID del pase: {id}',
    'it': 'ID badge: {id}',
  },
  'lastAction': {
    'de': 'Letzte Aktion: {dir}',
    'en': 'Last action: {dir}',
    'tr': 'Son işlem: {dir}',
    'ar': 'آخر إجراء: {dir}',
    'pl': 'Ostatnia akcja: {dir}',
    'fr': 'Dernière action : {dir}',
    'es': 'Última acción: {dir}',
    'it': 'Ultima azione: {dir}',
  },
  'nfcScanButton': {
    'de': 'NFC — Check-in/out',
    'en': 'NFC — Check-in/out',
    'tr': 'NFC — Giriş/çıkış',
    'ar': 'NFC — تسجيل دخول/خروج',
    'pl': 'NFC — Wejście/wyjście',
    'fr': 'NFC — Pointage',
    'es': 'NFC — Entrada/salida',
    'it': 'NFC — Check-in/out',
  },
  'scanning': {
    'de': 'Scanne…',
    'en': 'Scanning…',
    'tr': 'Taranıyor…',
    'ar': 'جارٍ المسح…',
    'pl': 'Skanowanie…',
    'fr': 'Scan…',
    'es': 'Escaneando…',
    'it': 'Scansione…',
  },
  'locating': {
    'de': 'Standort wird ermittelt…',
    'en': 'Getting location…',
    'tr': 'Konum alınıyor…',
    'ar': 'جاري تحديد الموقع…',
    'pl': 'Pobieranie lokalizacji…',
    'fr': 'Localisation…',
    'es': 'Obteniendo ubicación…',
    'it': 'Posizione in corso…',
  },
  'holdNfc': {
    'de': 'NFC-Karte ans Handy halten…',
    'en': 'Hold NFC card to phone…',
    'tr': 'NFC kartını telefona tutun…',
    'ar': 'أمسك بطاقة NFC بالهاتف…',
    'pl': 'Przyłóż kartę NFC do telefonu…',
    'fr': 'Approchez la carte NFC…',
    'es': 'Acerca la tarjeta NFC…',
    'it': 'Avvicina la carta NFC…',
  },
  'sendingCheckin': {
    'de': 'Check-in wird gesendet…',
    'en': 'Sending check-in…',
    'tr': 'Giriş gönderiliyor…',
    'ar': 'جارٍ إرسال التسجيل…',
    'pl': 'Wysyłanie check-in…',
    'fr': 'Envoi du pointage…',
    'es': 'Enviando fichaje…',
    'it': 'Invio check-in…',
  },
  'attendanceSaved': {
    'de': 'Anwesenheit gespeichert: {dir}',
    'en': 'Attendance saved: {dir}',
    'tr': 'Devam kaydedildi: {dir}',
    'ar': 'تم حفظ الحضور: {dir}',
    'pl': 'Obecność zapisana: {dir}',
    'fr': 'Présence enregistrée : {dir}',
    'es': 'Asistencia guardada: {dir}',
    'it': 'Presenza salvata: {dir}',
  },
  'attendanceDuplicate': {
    'de': 'Bereits erfasst ({dir}).',
    'en': 'Already recorded ({dir}).',
    'tr': 'Zaten kaydedildi ({dir}).',
    'ar': 'مسجّل مسبقاً ({dir}).',
    'pl': 'Już zapisano ({dir}).',
    'fr': 'Déjà enregistré ({dir}).',
    'es': 'Ya registrado ({dir}).',
    'it': 'Già registrato ({dir}).',
  },
  'offlineQueued': {
    'de': 'Offline gespeichert ({dir}) — wird synchronisiert.',
    'en': 'Saved offline ({dir}) — will sync.',
    'tr': 'Çevrimdışı kaydedildi ({dir}) — senkronize edilecek.',
    'ar': 'حُفظ دون اتصال ({dir}) — ستتم المزامنة.',
    'pl': 'Zapisano offline ({dir}) — zostanie zsynchronizowane.',
    'fr': 'Enregistré hors ligne ({dir}) — synchronisation à venir.',
    'es': 'Guardado sin conexión ({dir}) — se sincronizará.',
    'it': 'Salvato offline ({dir}) — verrà sincronizzato.',
  },
  'offlineProfile': {
    'de': 'Offline — zwischengespeichertes Profil.',
    'en': 'Offline — cached profile.',
    'tr': 'Çevrimdışı — önbellek profil.',
    'ar': 'دون اتصال — ملف مخزّن مؤقتاً.',
    'pl': 'Offline — profil z pamięci podręcznej.',
    'fr': 'Hors ligne — profil en cache.',
    'es': 'Sin conexión — perfil en caché.',
    'it': 'Offline — profilo in cache.',
  },
  'offlineSync': {
    'de': 'Offline-Sync',
    'en': 'Offline sync',
    'tr': 'Çevrimdışı senkron',
    'ar': 'مزامنة دون اتصال',
    'pl': 'Synchronizacja offline',
    'fr': 'Sync hors ligne',
    'es': 'Sincronizar offline',
    'it': 'Sync offline',
  },
  'gpsOff': {
    'de': 'GPS ist am Handy aus — bitte Standort aktivieren.',
    'en': 'GPS is off — please enable location.',
    'tr': 'GPS kapalı — lütfen konumu açın.',
    'ar': 'GPS متوقف — يرجى تفعيل الموقع.',
    'pl': 'GPS wyłączony — włącz lokalizację.',
    'fr': 'GPS désactivé — activez la localisation.',
    'es': 'GPS apagado — active la ubicación.',
    'it': 'GPS spento — attiva la posizione.',
  },
  'gpsPermissionDenied': {
    'de': 'Standortfreigabe fehlt — bitte „Beim Verwenden der App“ erlauben.',
    'en': 'Location permission missing — allow “While using the app”.',
    'tr': 'Konum izni yok — “Uygulamayı kullanırken” izin verin.',
    'ar': 'إذن الموقع مفقود — اسمح بـ «أثناء استخدام التطبيق».',
    'pl': 'Brak uprawnień do lokalizacji — zezwól „Podczas używania”.',
    'fr': 'Autorisation manquante — autorisez « Pendant l’utilisation ».',
    'es': 'Falta permiso de ubicación — permita «Al usar la app».',
    'it': 'Permesso posizione mancante — consenti «Durante l’uso».',
  },
  'gpsPermissionForever': {
    'de': 'Standort dauerhaft blockiert — in Android-Einstellungen für SUPPIX erlauben.',
    'en': 'Location blocked permanently — allow it in Android settings for SUPPIX.',
    'tr': 'Konum kalıcı engelli — Android ayarlarından SUPPIX için izin verin.',
    'ar': 'الموقع محظور نهائياً — اسمح به في إعدادات Android لـ SUPPIX.',
    'pl': 'Lokalizacja zablokowana — zezwól w ustawieniach Androida dla SUPPIX.',
    'fr': 'Localisation bloquée — autorisez-la dans les réglages Android pour SUPPIX.',
    'es': 'Ubicación bloqueada — permítala en ajustes de Android para SUPPIX.',
    'it': 'Posizione bloccata — consenti nelle impostazioni Android per SUPPIX.',
  },
  'gpsSlowOrInaccurate': {
    'de': 'Standort zu langsam / ungenau — kurz warten und erneut tippen.',
    'en': 'Location too slow / inaccurate — wait a moment and try again.',
    'tr': 'Konum yavaş / hatalı — biraz bekleyip tekrar deneyin.',
    'ar': 'الموقع بطيء / غير دقيق — انتظر قليلاً وحاول مجدداً.',
    'pl': 'Lokalizacja zbyt wolna / niedokładna — poczekaj i spróbuj ponownie.',
    'fr': 'Localisation trop lente / imprécise — attendez et réessayez.',
    'es': 'Ubicación lenta / imprecisa — espere y vuelva a intentarlo.',
    'it': 'Posizione lenta / imprecisa — attendi e riprova.',
  },
  'gpsCaptureFailed': {
    'de': 'Standort konnte nicht ermittelt werden — GPS prüfen und erneut tippen.',
    'en': 'Could not get location — check GPS and try again.',
    'tr': 'Konum alınamadı — GPS’i kontrol edip tekrar deneyin.',
    'ar': 'تعذّر تحديد الموقع — تحقق من GPS وحاول مجدداً.',
    'pl': 'Nie udało się pobrać lokalizacji — sprawdź GPS i spróbuj ponownie.',
    'fr': 'Impossible d’obtenir la position — vérifiez le GPS et réessayez.',
    'es': 'No se pudo obtener la ubicación — revise el GPS e inténtelo de nuevo.',
    'it': 'Impossibile ottenere la posizione — controlla il GPS e riprova.',
  },
  'gpsRequired': {
    'de': 'GPS erforderlich — Standortfreigabe aktivieren.',
    'en': 'GPS required — enable location permission.',
    'tr': 'GPS gerekli — konum iznini açın.',
    'ar': 'GPS مطلوب — فعّل إذن الموقع.',
    'pl': 'Wymagany GPS — włącz uprawnienie lokalizacji.',
    'fr': 'GPS requis — activez la localisation.',
    'es': 'Se requiere GPS — active el permiso de ubicación.',
    'it': 'GPS richiesto — attiva il permesso posizione.',
  },
  'errOutsideGeofence': {
    'de': 'Außerhalb der Baustelle — Check-in nur vor Ort möglich.',
    'en': 'Outside the site — check-in only on site.',
    'tr': 'Şantiye dışında — giriş yalnızca sahada mümkün.',
    'ar': 'خارج الموقع — التسجيل فقط في الموقع.',
    'pl': 'Poza budową — check-in tylko na miejscu.',
    'fr': 'Hors chantier — pointage uniquement sur site.',
    'es': 'Fuera de obra — fichaje solo en el sitio.',
    'it': 'Fuori cantiere — check-in solo in loco.',
  },
  'errSiteLocationUnavailable': {
    'de': 'Baustelle hat keinen GPS-Standort — Admin muss Standort in Firmeneinstellungen setzen.',
    'en': 'Site has no GPS location — admin must set it in company settings.',
    'tr': 'Şantiyenin GPS konumu yok — yönetici firma ayarlarından eklemeli.',
    'ar': 'الموقع بلا إحداثيات GPS — يجب على المسؤول ضبطها في إعدادات الشركة.',
    'pl': 'Budowa bez lokalizacji GPS — admin musi ustawić ją w firmie.',
    'fr': 'Chantier sans GPS — l’admin doit le définir dans les paramètres.',
    'es': 'Obra sin GPS — el admin debe configurarlo en la empresa.',
    'it': 'Cantiere senza GPS — l’admin deve impostarlo in azienda.',
  },
  'errGpsInaccurate': {
    'de': 'GPS zu ungenau — kurz warten und erneut versuchen.',
    'en': 'GPS too inaccurate — wait a moment and try again.',
    'tr': 'GPS çok hatalı — biraz bekleyip tekrar deneyin.',
    'ar': 'GPS غير دقيق — انتظر قليلاً وحاول مجدداً.',
    'pl': 'GPS zbyt niedokładny — poczekaj i spróbuj ponownie.',
    'fr': 'GPS trop imprécis — attendez et réessayez.',
    'es': 'GPS demasiado impreciso — espere y vuelva a intentarlo.',
    'it': 'GPS troppo impreciso — attendi e riprova.',
  },
  'errNfcNotEnrolled': {
    'de': 'NFC-Karte nicht hinterlegt — Admin muss die Karte dem Mitarbeiter zuweisen.',
    'en': 'NFC card not enrolled — admin must assign the card to the worker.',
    'tr': 'NFC kartı kayıtlı değil — yönetici karta atamalı.',
    'ar': 'بطاقة NFC غير مسجّلة — يجب على المسؤول تعيينها للموظف.',
    'pl': 'Karta NFC nieprzypisana — admin musi ją przypisać.',
    'fr': 'Carte NFC non enregistrée — l’admin doit l’assigner.',
    'es': 'Tarjeta NFC no registrada — el admin debe asignarla.',
    'it': 'Carta NFC non registrata — l’admin deve assegnarla.',
  },
  'errNfcMismatch': {
    'de': 'Falsche NFC-Karte — bitte die zugewiesene Mitarbeiterkarte verwenden.',
    'en': 'Wrong NFC card — use the assigned employee card.',
    'tr': 'Yanlış NFC kartı — atanmış personel kartını kullanın.',
    'ar': 'بطاقة NFC خاطئة — استخدم بطاقة الموظف المعيّنة.',
    'pl': 'Zła karta NFC — użyj przypisanej karty pracownika.',
    'fr': 'Mauvaise carte NFC — utilisez la carte assignée.',
    'es': 'Tarjeta NFC incorrecta — use la tarjeta asignada.',
    'it': 'Carta NFC errata — usa la carta dipendente assegnata.',
  },
  'errDeviceNotBound': {
    'de': 'Gerät nicht freigegeben — bitte erneut anmelden.',
    'en': 'Device not authorized — please sign in again.',
    'tr': 'Cihaz yetkili değil — lütfen yeniden giriş yapın.',
    'ar': 'الجهاز غير مصرّح — يرجى تسجيل الدخول مجدداً.',
    'pl': 'Urządzenie nieautoryzowane — zaloguj się ponownie.',
    'fr': 'Appareil non autorisé — reconnectez-vous.',
    'es': 'Dispositivo no autorizado — inicie sesión de nuevo.',
    'it': 'Dispositivo non autorizzato — accedi di nuovo.',
  },
  'errNetwork': {
    'de': 'Keine Verbindung zum Server — Internet prüfen.',
    'en': 'No server connection — check internet.',
    'tr': 'Sunucu bağlantısı yok — interneti kontrol edin.',
    'ar': 'لا اتصال بالخادم — تحقق من الإنترنت.',
    'pl': 'Brak połączenia z serwerem — sprawdź internet.',
    'fr': 'Pas de connexion serveur — vérifiez Internet.',
    'es': 'Sin conexión al servidor — revise Internet.',
    'it': 'Nessuna connessione al server — controlla Internet.',
  },
  'errAlreadyCheckedIn': {
    'de': 'Bereits eingestempelt — bitte erst ausstempeln.',
    'en': 'Already checked in — please check out first.',
    'tr': 'Zaten giriş yapılmış — önce çıkış yapın.',
    'ar': 'مسجّل دخول مسبقاً — سجّل الخروج أولاً.',
    'pl': 'Już zameldowano — najpierw wymelduj się.',
    'fr': 'Déjà pointé — veuillez d’abord sortir.',
    'es': 'Ya fichado — primero registre la salida.',
    'it': 'Già in ingresso — prima effettua l’uscita.',
  },
  'errNotCheckedIn': {
    'de': 'Nicht eingestempelt — bitte zuerst einchecken.',
    'en': 'Not checked in — please check in first.',
    'tr': 'Giriş yok — önce giriş yapın.',
    'ar': 'غير مسجّل دخول — سجّل الدخول أولاً.',
    'pl': 'Brak zameldowania — najpierw check-in.',
    'fr': 'Pas pointé — veuillez d’abord entrer.',
    'es': 'Sin fichaje — primero registre la entrada.',
    'it': 'Non in ingresso — prima effettua il check-in.',
  },
  'nfcUnavailable': {
    'de': 'NFC nicht verfügbar — in den Einstellungen aktivieren.',
    'en': 'NFC unavailable — enable it in settings.',
    'tr': 'NFC yok — ayarlardan açın.',
    'ar': 'NFC غير متاح — فعّله من الإعدادات.',
    'pl': 'NFC niedostępne — włącz w ustawieniach.',
    'fr': 'NFC indisponible — activez-le dans les réglages.',
    'es': 'NFC no disponible — actívelo en ajustes.',
    'it': 'NFC non disponibile — attivalo nelle impostazioni.',
  },
};
