import 'locale_controller.dart';

/// Compact in-app strings for native worker APK (DE/EN/TR/AR/PL/FR/ES/IT).
String t(String key, [String fallback = '']) {
  final lang = LocaleController.instance.lang;
  final row = _strings[key];
  if (row == null) return fallback.isNotEmpty ? fallback : key;
  return row[lang] ?? row['en'] ?? row['de'] ?? (fallback.isNotEmpty ? fallback : key);
}

const Map<String, Map<String, String>> _strings = {
  'navPass': {
    'de': 'Ausweis',
    'en': 'Pass',
    'tr': 'Kart',
    'ar': 'الهوية',
    'pl': 'Karta',
    'fr': 'Badge',
    'es': 'Pase',
    'it': 'Badge',
  },
  'navCheckin': {
    'de': 'Check-in',
    'en': 'Check-in',
    'tr': 'Giriş',
    'ar': 'تسجيل',
    'pl': 'Check-in',
    'fr': 'Pointage',
    'es': 'Entrada',
    'it': 'Check-in',
  },
  'navTasks': {
    'de': 'Aufgaben',
    'en': 'Tasks',
    'tr': 'Görevler',
    'ar': 'المهام',
    'pl': 'Zadania',
    'fr': 'Tâches',
    'es': 'Tareas',
    'it': 'Attività',
  },
  'navChat': {
    'de': 'Chat',
    'en': 'Chat',
    'tr': 'Sohbet',
    'ar': 'محادثة',
    'pl': 'Czat',
    'fr': 'Chat',
    'es': 'Chat',
    'it': 'Chat',
  },
  'navProfile': {
    'de': 'Profil',
    'en': 'Profile',
    'tr': 'Profil',
    'ar': 'الملف',
    'pl': 'Profil',
    'fr': 'Profil',
    'es': 'Perfil',
    'it': 'Profilo',
  },
  'language': {
    'de': 'Sprache',
    'en': 'Language',
    'tr': 'Dil',
    'ar': 'اللغة',
    'pl': 'Język',
    'fr': 'Langue',
    'es': 'Idioma',
    'it': 'Lingua',
  },
  'languageHint': {
    'de': 'Sprache jederzeit hier ändern — auch nach der Installation.',
    'en': 'Change language anytime here — also after installing the app.',
    'tr': 'Dili istediğiniz zaman buradan değiştirin — kurulumdan sonra da.',
    'ar': 'غيّر اللغة في أي وقت هنا — أيضًا بعد التثبيت.',
    'pl': 'Zmień język w dowolnym momencie — także po instalacji.',
    'fr': 'Changez la langue ici à tout moment — aussi après l’installation.',
    'es': 'Cambia el idioma aquí en cualquier momento — también tras instalar.',
    'it': 'Cambia lingua qui in qualsiasi momento — anche dopo l’installazione.',
  },
  'loginTitle': {
    'de': 'Digitalen Ausweis aktivieren',
    'en': 'Activate digital pass',
    'tr': 'Dijital kartı etkinleştir',
    'ar': 'تفعيل الهوية الرقمية',
    'pl': 'Aktywuj kartę cyfrową',
    'fr': 'Activer le badge numérique',
    'es': 'Activar pase digital',
    'it': 'Attiva badge digitale',
  },
  'loginSubtitle': {
    'de': 'Mitarbeiterausweis',
    'en': 'Employee pass',
    'tr': 'Personel kartı',
    'ar': 'بطاقة الموظف',
    'pl': 'Karta pracownika',
    'fr': 'Badge employé',
    'es': 'Pase de empleado',
    'it': 'Badge dipendente',
  },
  'attachFailed': {
    'de': 'Anhang senden fehlgeschlagen',
    'en': 'Failed to send attachment',
    'tr': 'Ek gönderilemedi',
    'ar': 'فشل إرسال المرفق',
    'pl': 'Nie udało się wysłać załącznika',
    'fr': 'Échec de l’envoi de la pièce jointe',
    'es': 'No se pudo enviar el adjunto',
    'it': 'Invio allegato non riuscito',
  },
  'shiftSwap': {
    'de': 'Schicht tauschen',
    'en': 'Swap shift',
    'tr': 'Vardiya değiştir',
    'ar': 'تبديل الوردية',
    'pl': 'Zamień zmianę',
    'fr': 'Échanger le quart',
    'es': 'Cambiar turno',
    'it': 'Scambia turno',
  },
  'shiftsMine': {
    'de': 'Meine Schichten',
    'en': 'My shifts',
    'tr': 'Vardiyalarım',
    'ar': 'وردياتي',
    'pl': 'Moje zmiany',
    'fr': 'Mes quarts',
    'es': 'Mis turnos',
    'it': 'I miei turni',
  },
  'shiftsSwapTab': {
    'de': 'Tausch',
    'en': 'Swap',
    'tr': 'Değişim',
    'ar': 'تبديل',
    'pl': 'Zamiana',
    'fr': 'Échange',
    'es': 'Cambio',
    'it': 'Scambio',
  },
};
