"""Premium monthly Einsatzplan PDF per worker — portrait, one page, company branding."""
from __future__ import annotations

import calendar
import html
import io
from datetime import date, datetime, timezone
from typing import Any


MONTH_NAMES = {
    "de": [
        "",
        "Januar",
        "Februar",
        "März",
        "April",
        "Mai",
        "Juni",
        "Juli",
        "August",
        "September",
        "Oktober",
        "November",
        "Dezember",
    ],
    "en": [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ],
    "ar": [
        "",
        "يناير",
        "فبراير",
        "مارس",
        "أبريل",
        "مايو",
        "يونيو",
        "يوليو",
        "أغسطس",
        "سبتمبر",
        "أكتوبر",
        "نوفمبر",
        "ديسمبر",
    ],
}

TITLE = {
    "de": "Einsatzplan",
    "en": "Deployment plan",
    "ar": "خطة التوزيع",
}

WEEKDAY_HEADERS = {
    "de": ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "ar": ["ن", "ث", "ر", "خ", "ج", "س", "ح"],
}

FOOTER_TEXT = {
    "de": "Erstellt mit BauPass · Vertraulich — nur für den genannten Mitarbeiter.",
    "en": "Generated by BauPass · Confidential — for the named employee only.",
    "ar": "صادر من BauPass · سري — للموظف المذكور فقط.",
}


def _escape(text: str) -> str:
    return html.escape(str(text or ""), quote=True)


def _format_time_range(day: dict[str, Any]) -> str:
    t_start = str(day.get("shiftStart") or "").strip()
    t_end = str(day.get("shiftEnd") or "").strip()
    if not t_start and not t_end:
        return ""
    start = t_start[11:16] if len(t_start) > 11 else t_start
    end = t_end[11:16] if len(t_end) > 11 else t_end
    if start and end:
        return f"{start}–{end}"
    return start or end


def _days_index(days: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(d.get("date") or ""): d for d in days}


def build_deployment_plan_pdf(
    *,
    company_name: str,
    worker_name: str,
    badge_id: str | None,
    year: int,
    month: int,
    days: list[dict[str, Any]],
    lang: str = "de",
    plan_tier: str = "professional",
    branding: dict[str, Any] | None = None,
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    from .deployment_branding import logo_image_flowable

    lang_key = (lang or "de")[:2]
    if lang_key not in WEEKDAY_HEADERS:
        lang_key = "de"
    month_label = MONTH_NAMES.get(lang_key, MONTH_NAMES["de"])[month]
    title = TITLE.get(lang_key, TITLE["de"])

    buffer = io.BytesIO()
    page_size = A4
    doc = SimpleDocTemplate(
        buffer,
        pagesize=page_size,
        leftMargin=11 * mm,
        rightMargin=11 * mm,
        topMargin=10 * mm,
        bottomMargin=10 * mm,
        title=f"Einsatzplan {worker_name} {month_label} {year}",
    )

    brand = branding or {}
    styles = getSampleStyleSheet()
    accent = colors.HexColor(str(brand.get("accent") or "#0f4c5c"))
    accent_light = colors.HexColor(str(brand.get("accentLight") or "#1a8aad"))
    muted = colors.HexColor("#5a6a78")
    weekend_bg = colors.HexColor("#f3f6f9")
    empty_bg = colors.HexColor("#fafbfc")
    display_company = str(brand.get("companyName") or company_name or "BauPass")
    sector_label = str(brand.get("sectorLabel") or "").strip()

    sub_style = ParagraphStyle(
        "BpSub",
        parent=styles["Normal"],
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#334155"),
    )
    cell_style = ParagraphStyle(
        "BpCell",
        parent=styles["Normal"],
        fontSize=7,
        leading=8,
        textColor=colors.HexColor("#1e293b"),
    )
    wk_style = ParagraphStyle(
        "BpWk",
        parent=styles["Normal"],
        fontSize=7.5,
        leading=9,
        textColor=colors.white,
        fontName="Helvetica-Bold",
        alignment=1,
    )

    period_line = f"{month_label} {year}"
    worker_line = f"<b>{_escape(worker_name)}</b>"
    if badge_id:
        worker_line += f" · Badge {_escape(str(badge_id))}"
    meta_html = f"{_escape(title)} · {period_line}<br/>{worker_line}"
    if sector_label:
        meta_html = f"<font size='8' color='#64748b'>{_escape(sector_label)}</font><br/>{meta_html}"
    meta_html += (
        f"<br/><font size='7' color='#94a3b8'>"
        f"{datetime.now(timezone.utc).strftime('%d.%m.%Y %H:%M')} UTC</font>"
    )

    logo_img = logo_image_flowable(str(brand.get("logoData") or ""), max_height_mm=20.0)
    meta_para = Paragraph(
        f"<font size='12'><b>{_escape(display_company)}</b></font><br/>{meta_html}",
        sub_style,
    )
    if logo_img:
        header_table = Table(
            [[logo_img, meta_para]],
            colWidths=[24 * mm, doc.width - 24 * mm],
        )
        header_table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (0, 0), 0),
                    ("RIGHTPADDING", (0, 0), (0, 0), 8),
                    ("LEFTPADDING", (1, 0), (1, 0), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 2),
                ]
            )
        )
    else:
        header_table = Table([[meta_para]], colWidths=[doc.width])
        header_table.setStyle(
            TableStyle(
                [
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 2),
                ]
            )
        )

    accent_bar = Table([[""]], colWidths=[doc.width], rowHeights=[2.5 * mm])
    accent_bar.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), accent),
                ("BOX", (0, 0), (-1, -1), 0, accent),
            ]
        )
    )

    by_date = _days_index(days)
    weeks = calendar.monthcalendar(year, month)
    col_w = doc.width / 7.0
    week_count = max(len(weeks), 1)
    usable_calendar_h = doc.height - 34 * mm - 10 * mm
    wk_header_h = 6 * mm
    week_row_h = max(26 * mm, (usable_calendar_h - wk_header_h) / week_count)

    grid: list[list] = [
        [Paragraph(_escape(h), wk_style) for h in WEEKDAY_HEADERS[lang_key]]
    ]
    weekend_style_cmds: list[tuple] = []

    for wi, week in enumerate(weeks):
        row_cells: list = []
        for ci, day_num in enumerate(week):
            if day_num == 0:
                row_cells.append("")
                continue
            iso = date(year, month, day_num).isoformat()
            info = by_date.get(iso, {})
            loc = str(info.get("location") or "").strip()
            time_txt = _format_time_range(info)
            accent_hex = str(brand.get("accent") or "#0f4c5c")
            parts = [f"<b><font size='9' color='{_escape(accent_hex)}'>{day_num}</font></b>"]
            if loc:
                parts.append(f"<font size='6.5'>{_escape(loc[:28])}</font>")
            elif info:
                dash = "—" if lang_key != "ar" else "—"
                parts.append(f"<font size='6' color='#94a3b8'>{dash}</font>")
            if time_txt:
                parts.append(f"<font size='6' color='#64748b'>{_escape(time_txt)}</font>")
            note = str(info.get("notes") or "").strip()
            if note:
                parts.append(f"<font size='5.5' color='#94a3b8'>{_escape(note[:22])}</font>")
            row_cells.append(Paragraph("<br/>".join(parts), cell_style))
            if info.get("isWeekend") or ci >= 5:
                row_idx = wi + 1
                weekend_style_cmds.append(("BACKGROUND", (ci, row_idx), (ci, row_idx), weekend_bg))
        grid.append(row_cells)

    row_heights = [wk_header_h] + [week_row_h] * len(weeks)
    calendar_table = Table(grid, colWidths=[col_w] * 7, rowHeights=row_heights)
    cal_style = [
        ("BACKGROUND", (0, 0), (-1, 0), accent_light),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for wi, week in enumerate(weeks):
        for ci, day_num in enumerate(week):
            if day_num == 0:
                cal_style.append(("BACKGROUND", (ci, wi + 1), (ci, wi + 1), empty_bg))
    cal_style.extend(weekend_style_cmds)
    calendar_table.setStyle(TableStyle(cal_style))

    footer_style = ParagraphStyle("footer", parent=styles["Normal"], fontSize=7, textColor=muted)
    footer = Paragraph(FOOTER_TEXT.get(lang_key, FOOTER_TEXT["de"]), footer_style)

    story_parts: list = [header_table, accent_bar, Spacer(1, 3 * mm), calendar_table, Spacer(1, 2 * mm), footer]
    if plan_tier == "enterprise":
        ent = Paragraph(
            f"<font color='{_escape(str(brand.get('accentLight') or '#1a8aad'))}'><b>Enterprise</b> — Multi-Site</font>",
            ParagraphStyle("ent", parent=styles["Normal"], fontSize=7.5),
        )
        story_parts.insert(3, ent)

    doc.build([KeepTogether(story_parts)])
    return buffer.getvalue()
