"""Extra catalog labels for tr/fr/es/it/pl."""
from __future__ import annotations

EXTRA_LANGS = ("tr", "fr", "es", "it", "pl")

LAYER_TITLE_EXTRA: dict[str, dict[str, str]] = {
    "core_workforce": {
        "tr": "Temel İşgücü Altyapısı",
        "fr": "Infrastructure workforce de base",
        "es": "Infraestructura central de fuerza laboral",
        "it": "Infrastruttura workforce di base",
        "pl": "Podstawowa infrastruktura siły roboczej",
    },
    "digital_identity": {
        "tr": "Dijital İşgücü Kimliği",
        "fr": "Identité numérique de la workforce",
        "es": "Identidad digital de la fuerza laboral",
        "it": "Identità digitale della workforce",
        "pl": "Cyfrowa tożsamość pracowników",
    },
    "access_security": {
        "tr": "Erişim ve Fiziksel Güvenlik",
        "fr": "Accès et sécurité physique",
        "es": "Acceso y seguridad física",
        "it": "Accesso e sicurezza fisica",
        "pl": "Dostęp i bezpieczeństwo fizyczne",
    },
    "automation": {
        "tr": "Akıllı Otomasyon",
        "fr": "Automatisation intelligente",
        "es": "Automatización inteligente",
        "it": "Automazione intelligente",
        "pl": "Inteligentna automatyzacja",
    },
    "realtime": {
        "tr": "Gerçek Zamanlı Operasyon",
        "fr": "Exploitation en temps réel",
        "es": "Operación en tiempo real",
        "it": "Operatività in tempo reale",
        "pl": "Operacje w czasie rzeczywistym",
    },
    "operational_ux": {
        "tr": "Operasyonel Deneyim",
        "fr": "Expérience opérationnelle",
        "es": "Experiencia operativa",
        "it": "Esperienza operativa",
        "pl": "Doświadczenie operacyjne",
    },
    "security_compliance": {
        "tr": "Kurumsal Güvenlik ve Uyumluluk",
        "fr": "Sécurité et conformité entreprise",
        "es": "Seguridad y cumplimiento empresarial",
        "it": "Sicurezza e conformità enterprise",
        "pl": "Bezpieczeństwo i zgodność enterprise",
    },
    "intelligence": {
        "tr": "Kurumsal Zeka ve Yapay Zeka",
        "fr": "Intelligence entreprise et IA",
        "es": "Inteligencia empresarial e IA",
        "it": "Intelligence enterprise e IA",
        "pl": "Inteligencja enterprise i AI",
    },
    "physical_ops": {
        "tr": "Akıllı Fiziksel Operasyonlar",
        "fr": "Exploitation physique intelligente",
        "es": "Operaciones físicas inteligentes",
        "it": "Operazioni fisiche intelligenti",
        "pl": "Inteligentne operacje fizyczne",
    },
    "autonomous": {
        "tr": "Otonom Kurumsal Katman",
        "fr": "Couche entreprise autonome",
        "es": "Capa empresarial autónoma",
        "it": "Livello enterprise autonomo",
        "pl": "Autonomiczna warstwa enterprise",
    },
    "integrations": {
        "tr": "Kurumsal Entegrasyon Ekosistemi",
        "fr": "Écosystème d'intégrations entreprise",
        "es": "Ecosistema de integraciones empresariales",
        "it": "Ecosistema integrazioni enterprise",
        "pl": "Ekosystem integracji enterprise",
    },
    "platform_ecosystem": {
        "tr": "Platform Ekosistemi",
        "fr": "Écosystème plateforme",
        "es": "Ecosistema de plataforma",
        "it": "Ecosistema piattaforma",
        "pl": "Ekosystem platformy",
    },
    "hyper_scale": {
        "tr": "Hiper Ölçeklenebilir Altyapı",
        "fr": "Infrastructure hyper-scale",
        "es": "Infraestructura hiperescala",
        "it": "Infrastruttura hyper-scale",
        "pl": "Infrastruktura hiper-skali",
    },
    "saas_business": {
        "tr": "Kurumsal SaaS ve İş Modelleri",
        "fr": "SaaS et activité entreprise",
        "es": "SaaS y negocio empresarial",
        "it": "SaaS e business enterprise",
        "pl": "SaaS i model biznesowy enterprise",
    },
    "global_command": {
        "tr": "Küresel Operasyon Komuta Merkezi",
        "fr": "Commande opérationnelle globale",
        "es": "Centro de mando operativo global",
        "it": "Comando operativo globale",
        "pl": "Globalne centrum dowodzenia operacji",
    },
    "vision": {
        "tr": "Stratejik Gelecek Vizyonu",
        "fr": "Vision stratégique d'avenir",
        "es": "Visión estratégica de futuro",
        "it": "Visione strategica del futuro",
        "pl": "Strategiczna wizja przyszłości",
    },
}

ITEM_LABEL_EXTRA: dict[str, dict[str, str]] = {
    "employees": {
        "tr": "Çalışan Yönetimi",
        "fr": "Gestion des employés",
        "es": "Gestión de empleados",
        "it": "Gestione dipendenti",
        "pl": "Zarządzanie pracownikami",
    },
    "workforce_mgmt": {
        "tr": "İşgücü Yönetimi",
        "fr": "Gestion de la workforce",
        "es": "Gestión de fuerza laboral",
        "it": "Gestione workforce",
        "pl": "Zarządzanie siłą roboczą",
    },
    "attendance": {
        "tr": "Devam Yönetimi",
        "fr": "Gestion des présences",
        "es": "Gestión de asistencia",
        "it": "Gestione presenze",
        "pl": "Zarządzanie obecnością",
    },
    "gps_attendance": {
        "tr": "GPS Devam Takibi",
        "fr": "Présence GPS",
        "es": "Asistencia por GPS",
        "it": "Presenza GPS",
        "pl": "Obecność GPS",
    },
    "geofence_att": {
        "tr": "Geofence Devam Takibi",
        "fr": "Présence par géorepérage",
        "es": "Asistencia por geovalla",
        "it": "Presenza con geofence",
        "pl": "Obecność z geofence",
    },
    "smart_inout": {
        "tr": "Akıllı Giriş / Çıkış",
        "fr": "Enregistrement intelligent entrée/sortie",
        "es": "Registro inteligente de entrada/salida",
        "it": "Check-in/out intelligente",
        "pl": "Inteligentne wejście/wyjście",
    },
    "auto_checkin_loc": {
        "tr": "Konuma Göre Otomatik Check-In",
        "fr": "Enregistrement auto par localisation",
        "es": "Check-in automático por ubicación",
        "it": "Check-in automatico per posizione",
        "pl": "Automatyczny check-in według lokalizacji",
    },
    "shifts": {
        "tr": "Vardiya Yönetimi",
        "fr": "Gestion des équipes",
        "es": "Gestión de turnos",
        "it": "Gestione turni",
        "pl": "Zarządzanie zmianami",
    },
    "shift_mgmt": {
        "tr": "Gelişmiş Vardiya Planlama",
        "fr": "Planification avancée des équipes",
        "es": "Planificación avanzada de turnos",
        "it": "Pianificazione turni avanzata",
        "pl": "Zaawansowane planowanie zmian",
    },
    "leave": {
        "tr": "İzin Yönetimi",
        "fr": "Gestion des congés",
        "es": "Gestión de permisos",
        "it": "Gestione ferie e permessi",
        "pl": "Zarządzanie urlopami",
    },
    "sick_leave": {
        "tr": "Hastalık İzni",
        "fr": "Arrêts maladie",
        "es": "Bajas por enfermedad",
        "it": "Assenze per malattia",
        "pl": "Zwolnienia lekarskie",
    },
    "worker_profiles": {
        "tr": "Çalışan Profilleri",
        "fr": "Profils employés",
        "es": "Perfiles de empleados",
        "it": "Profili dipendenti",
        "pl": "Profile pracowników",
    },
    "worker_documents": {
        "tr": "Çalışan Belgeleri",
        "fr": "Documents employés",
        "es": "Documentos de empleados",
        "it": "Documenti dipendenti",
        "pl": "Dokumenty pracowników",
    },
    "timesheets": {
        "tr": "Zaman Çizelgeleri",
        "fr": "Feuilles de temps",
        "es": "Partes de horas",
        "it": "Fogli presenze",
        "pl": "Karty czasu pracy",
    },
    "scheduling": {
        "tr": "İşgücü Planlama",
        "fr": "Planification workforce",
        "es": "Planificación de fuerza laboral",
        "it": "Pianificazione workforce",
        "pl": "Planowanie siły roboczej",
    },
    "presence_tracking": {
        "tr": "Anlık Varlık Takibi",
        "fr": "Suivi de présence",
        "es": "Seguimiento de presencia",
        "it": "Tracciamento presenze",
        "pl": "Śledzenie obecności",
    },
    "workforce_reporting": {
        "tr": "İşgücü Raporlama",
        "fr": "Reporting workforce",
        "es": "Informes de fuerza laboral",
        "it": "Reportistica workforce",
        "pl": "Raportowanie siły roboczej",
    },
    "worker_notifications": {
        "tr": "Çalışan Bildirimleri",
        "fr": "Notifications employés",
        "es": "Notificaciones a empleados",
        "it": "Notifiche dipendenti",
        "pl": "Powiadomienia pracowników",
    },
    "worker_chat": {
        "tr": "Çalışan Sohbeti",
        "fr": "Chat employés",
        "es": "Chat de empleados",
        "it": "Chat dipendenti",
        "pl": "Czat pracowników",
    },
    "employment_contracts": {
        "tr": "Yapay Zeka İş Sözleşmeleri",
        "fr": "Contrats de travail IA",
        "es": "Contratos laborales con IA",
        "it": "Contratti di lavoro IA",
        "pl": "Umowy o pracę z AI",
    },
    "foreman_dashboard": {
        "tr": "Formen Paneli",
        "fr": "Tableau de bord contremaître",
        "es": "Panel del capataz",
        "it": "Dashboard capocantiere",
        "pl": "Panel brygadzisty",
    },
    "contractor_mgmt": {
        "tr": "Taşeron Yönetimi",
        "fr": "Gestion des sous-traitants",
        "es": "Gestión de subcontratistas",
        "it": "Gestione subappaltatori",
        "pl": "Zarządzanie podwykonawcami",
    },
    "visitor": {
        "tr": "Ziyaretçi Yönetimi",
        "fr": "Gestion des visiteurs",
        "es": "Gestión de visitantes",
        "it": "Gestione visitatori",
        "pl": "Zarządzanie gośćmi",
    },
    "rbac": {
        "tr": "RBAC Sistemi",
        "fr": "Système RBAC",
        "es": "Sistema RBAC",
        "it": "Sistema RBAC",
        "pl": "System RBAC",
    },
    "workforce_roles": {
        "tr": "Roller ve İzinler",
        "fr": "Rôles et autorisations",
        "es": "Roles y permisos",
        "it": "Ruoli e permessi",
        "pl": "Role i uprawnienia",
    },
    "multi_tenant": {
        "tr": "Çok Kiracılı Mimari",
        "fr": "Architecture multi-locataire",
        "es": "Arquitectura multiinquilino",
        "it": "Architettura multi-tenant",
        "pl": "Architektura multi-tenant",
    },
    "multi_branch": {
        "tr": "Çok Lokasyonlu Yapı",
        "fr": "Multi-sites",
        "es": "Multi-sede",
        "it": "Multi-sede",
        "pl": "Wiele lokalizacji",
    },
    "tenant_isolation": {
        "tr": "Kiracı İzolasyonu",
        "fr": "Isolation des locataires",
        "es": "Aislamiento de inquilinos",
        "it": "Isolamento tenant",
        "pl": "Izolacja tenantów",
    },
    "company_work_rules": {
        "tr": "Şirket Çalışma Kuralları",
        "fr": "Règles de travail entreprise",
        "es": "Reglas laborales de la empresa",
        "it": "Regole lavoro aziendali",
        "pl": "Reguły pracy firmy",
    },
    "site_work_rules": {
        "tr": "Saha Çalışma Kuralları",
        "fr": "Règles de chantier",
        "es": "Reglas de obra",
        "it": "Regole cantiere",
        "pl": "Reguły pracy na placu budowy",
    },
    "workforce_compliance": {
        "tr": "İşgücü Uyumluluğu",
        "fr": "Conformité workforce",
        "es": "Cumplimiento de fuerza laboral",
        "it": "Conformità workforce",
        "pl": "Zgodność siły roboczej",
    },
    "worker_hybrid": {
        "tr": "Worker Uygulaması (Hibrit Flutter)",
        "fr": "App Worker (Flutter hybride)",
        "es": "App Worker (Flutter híbrida)",
        "it": "App Worker (Flutter ibrida)",
        "pl": "Aplikacja Worker (hybrydowy Flutter)",
    },
    "worker_dashboard": {
        "tr": "Çalışan Paneli",
        "fr": "Tableau de bord employé",
        "es": "Panel del empleado",
        "it": "Dashboard dipendente",
        "pl": "Panel pracownika",
    },
    "self_service": {
        "tr": "Self-Service Portalı",
        "fr": "Portail self-service",
        "es": "Portal de autoservicio",
        "it": "Portale self-service",
        "pl": "Portal samoobsługowy",
    },
    "offline": {
        "tr": "Çevrimdışı Çalışma",
        "fr": "Fonctionnement hors ligne",
        "es": "Operación sin conexión",
        "it": "Funzionamento offline",
        "pl": "Praca offline",
    },
    "access_logs_wf": {
        "tr": "İşgücü Erişim Günlükleri",
        "fr": "Journaux d'accès workforce",
        "es": "Registros de acceso de fuerza laboral",
        "it": "Log accessi workforce",
        "pl": "Dzienniki dostępu siły roboczej",
    },
    "analytics_wf": {
        "tr": "İşgücü Analitiği",
        "fr": "Analytique workforce",
        "es": "Analítica de fuerza laboral",
        "it": "Analytics workforce",
        "pl": "Analityka siły roboczej",
    },
    "workforce_kpi": {
        "tr": "İşgücü KPI'ları",
        "fr": "KPI workforce",
        "es": "KPI de fuerza laboral",
        "it": "KPI workforce",
        "pl": "KPI siły roboczej",
    },
    "digital_employee_id": {
        "tr": "Dijital Çalışan Kimliği",
        "fr": "Identité numérique employé",
        "es": "Identidad digital del empleado",
        "it": "Identità digitale dipendente",
        "pl": "Cyfrowa tożsamość pracownika",
    },
    "qr_badge": {
        "tr": "QR Rozet Sistemi",
        "fr": "Système de badge QR",
        "es": "Sistema de credencial QR",
        "it": "Sistema badge QR",
        "pl": "System identyfikatorów QR",
    },
    "dynamic_qr": {
        "tr": "Dinamik QR Kodlar",
        "fr": "Codes QR dynamiques",
        "es": "Códigos QR dinámicos",
        "it": "Codici QR dinamici",
        "pl": "Dynamiczne kody QR",
    },
    "nfc_id": {
        "tr": "NFC Kimliği",
        "fr": "Identité NFC",
        "es": "Identidad NFC",
        "it": "Identità NFC",
        "pl": "Tożsamość NFC",
    },
    "smart_badge": {
        "tr": "Akıllı Rozet Altyapısı",
        "fr": "Infrastructure de badge intelligent",
        "es": "Infraestructura de credencial inteligente",
        "it": "Infrastruttura badge smart",
        "pl": "Infrastruktura inteligentnych identyfikatorów",
    },
    "temp_access_pass": {
        "tr": "Geçici Erişim Kartları",
        "fr": "Pass d'accès temporaires",
        "es": "Pases de acceso temporales",
        "it": "Pass accesso temporanei",
        "pl": "Tymczasowe karty dostępu",
    },
    "identity_tokens": {
        "tr": "Kimlik Token'ları",
        "fr": "Jetons d'identité",
        "es": "Tokens de identidad",
        "it": "Token identità",
        "pl": "Tokeny tożsamości",
    },
    "identity_verify": {
        "tr": "Güvenli Kimlik Doğrulama",
        "fr": "Vérification d'identité sécurisée",
        "es": "Verificación segura de identidad",
        "it": "Verifica identità sicura",
        "pl": "Bezpieczna weryfikacja tożsamości",
    },
    "device_trust": {
        "tr": "Cihaz Güveni",
        "fr": "Confiance des appareils",
        "es": "Confianza del dispositivo",
        "it": "Fiducia dispositivo",
        "pl": "Zaufanie urządzenia",
    },
    "identity_sessions": {
        "tr": "Kimlik Oturumları",
        "fr": "Sessions d'identité",
        "es": "Sesiones de identidad",
        "it": "Sessioni identità",
        "pl": "Sesje tożsamości",
    },
    "cross_platform_id": {
        "tr": "Platformlar Arası Kimlik",
        "fr": "Identité multi-plateforme",
        "es": "Identidad multiplataforma",
        "it": "Identità cross-platform",
        "pl": "Tożsamość międzyplatformowa",
    },
    "enterprise_identity": {
        "tr": "Kurumsal Kimlik Motoru",
        "fr": "Moteur d'identité entreprise",
        "es": "Motor de identidad empresarial",
        "it": "Motore identità enterprise",
        "pl": "Silnik tożsamości enterprise",
    },
    "unified_identity": {
        "tr": "Birleşik İşgücü Kimliği",
        "fr": "Identité workforce unifiée",
        "es": "Identidad unificada de fuerza laboral",
        "it": "Identità workforce unificata",
        "pl": "Ujednolicona tożsamość pracowników",
    },
    "apple_wallet": {
        "tr": "Apple Wallet Kartı",
        "fr": "Pass Apple Wallet",
        "es": "Pase Apple Wallet",
        "it": "Pass Apple Wallet",
        "pl": "Karta Apple Wallet",
    },
    "google_wallet": {
        "tr": "Google Wallet Kartı",
        "fr": "Pass Google Wallet",
        "es": "Pase Google Wallet",
        "it": "Pass Google Wallet",
        "pl": "Karta Google Wallet",
    },
    "hce": {
        "tr": "Android HCE Kimliği",
        "fr": "Identité Android HCE",
        "es": "Identidad Android HCE",
        "it": "Identità Android HCE",
        "pl": "Tożsamość Android HCE",
    },
    "join_flow": {
        "tr": "Kimlik Onboarding",
        "fr": "Onboarding identité",
        "es": "Incorporación de identidad",
        "it": "Onboarding identità",
        "pl": "Onboarding tożsamości",
    },
    "gates": {
        "tr": "Kapı Yönetimi",
        "fr": "Gestion des portiques",
        "es": "Gestión de accesos",
        "it": "Gestione varchi",
        "pl": "Zarządzanie bramkami",
    },
    "turnstile": {
        "tr": "Turnike Entegrasyonu",
        "fr": "Intégration tourniquets",
        "es": "Integración de torniquetes",
        "it": "Integrazione tornelli",
        "pl": "Integracja z bramkami obrotowymi",
    },
    "nfc_access": {
        "tr": "NFC Erişim Kontrolü",
        "fr": "Contrôle d'accès NFC",
        "es": "Control de acceso NFC",
        "it": "Controllo accessi NFC",
        "pl": "Kontrola dostępu NFC",
    },
    "live_access": {
        "tr": "Canlı Erişim İzleme",
        "fr": "Surveillance d'accès en direct",
        "es": "Monitorización de acceso en vivo",
        "it": "Monitoraggio accessi live",
        "pl": "Monitorowanie dostępu na żywo",
    },
    "access_logs": {
        "tr": "Erişim Günlükleri",
        "fr": "Journaux d'accès",
        "es": "Registros de acceso",
        "it": "Log accessi",
        "pl": "Dzienniki dostępu",
    },
    "zones": {
        "tr": "Akıllı Erişim Bölgeleri",
        "fr": "Zones d'accès intelligentes",
        "es": "Zonas de acceso inteligentes",
        "it": "Zone accesso smart",
        "pl": "Inteligentne strefy dostępu",
    },
    "emergency": {
        "tr": "Acil Durum Kilitleme",
        "fr": "Verrouillage d'urgence",
        "es": "Bloqueo de emergencia",
        "it": "Blocco emergenza",
        "pl": "Blokada awaryjna",
    },
    "cmd_center": {
        "tr": "Canlı Kapı İzleme",
        "fr": "Surveillance portiques en direct",
        "es": "Monitorización de accesos en vivo",
        "it": "Monitoraggio varchi live",
        "pl": "Monitorowanie bramek na żywo",
    },
    "deployment_plan": {
        "tr": "Aylık Görev Planı",
        "fr": "Plan de déploiement mensuel",
        "es": "Plan de despliegue mensual",
        "it": "Piano di dispiegamento mensile",
        "pl": "Miesięczny plan wdrożeń",
    },
    "workflows": {
        "tr": "İş Akışı Otomasyonu",
        "fr": "Automatisation des workflows",
        "es": "Automatización de flujos de trabajo",
        "it": "Automazione workflow",
        "pl": "Automatyzacja przepływów pracy",
    },
    "auto_expiry": {
        "tr": "Otomatik Süre Dolumu Uyarıları",
        "fr": "Alertes d'expiration automatiques",
        "es": "Alertas de vencimiento automáticas",
        "it": "Avvisi scadenza automatici",
        "pl": "Automatyczne alerty wygaśnięcia",
    },
    "dunning": {
        "tr": "Otomatik Faturalama / Tahsilat",
        "fr": "Facturation auto / relances",
        "es": "Facturación automática / cobros",
        "it": "Fatturazione auto / solleciti",
        "pl": "Automatyczne fakturowanie / windykacja",
    },
    "onboarding_auto": {
        "tr": "Otomatik Onboarding",
        "fr": "Onboarding automatique",
        "es": "Incorporación automática",
        "it": "Onboarding automatico",
        "pl": "Automatyczny onboarding",
    },
    "event_bus": {
        "tr": "Olay Tabanlı Otomasyon",
        "fr": "Automatisation pilotée par événements",
        "es": "Automatización basada en eventos",
        "it": "Automazione event-driven",
        "pl": "Automatyzacja oparta na zdarzeniach",
    },
    "websocket": {
        "tr": "WebSocket Altyapısı",
        "fr": "Infrastructure WebSocket",
        "es": "Infraestructura WebSocket",
        "it": "Infrastruttura WebSocket",
        "pl": "Infrastruktura WebSocket",
    },
    "live_presence": {
        "tr": "Canlı Varlık Durumu",
        "fr": "Présence en direct",
        "es": "Presencia en vivo",
        "it": "Presenza live",
        "pl": "Obecność na żywo",
    },
    "live_metrics": {
        "tr": "Gerçek Zamanlı Metrikler",
        "fr": "Métriques en temps réel",
        "es": "Métricas en tiempo real",
        "it": "Metriche in tempo reale",
        "pl": "Metryki w czasie rzeczywistym",
    },
    "sse": {
        "tr": "Canlı Aktivite Akışları",
        "fr": "Flux d'activité en direct",
        "es": "Flujos de actividad en vivo",
        "it": "Stream attività live",
        "pl": "Strumienie aktywności na żywo",
    },
    "admin_v2": {
        "tr": "Modern Kurumsal Arayüz",
        "fr": "Interface entreprise moderne",
        "es": "Interfaz empresarial moderna",
        "it": "Interfaccia enterprise moderna",
        "pl": "Nowoczesny interfejs enterprise",
    },
    "design_tokens": {
        "tr": "Tasarım Sistemi",
        "fr": "Système de design",
        "es": "Sistema de diseño",
        "it": "Design system",
        "pl": "System projektowy",
    },
    "offline_sync": {
        "tr": "Çevrimdışı Senkronizasyon",
        "fr": "Synchronisation hors ligne",
        "es": "Sincronización sin conexión",
        "it": "Sincronizzazione offline",
        "pl": "Synchronizacja offline",
    },
    "flutter": {
        "tr": "Çapraz Platform Uygulaması",
        "fr": "Application cross-platform",
        "es": "Aplicación multiplataforma",
        "it": "App cross-platform",
        "pl": "Aplikacja wieloplatformowa",
    },
    "zero_trust": {
        "tr": "Sıfır Güven",
        "fr": "Zero Trust",
        "es": "Confianza cero",
        "it": "Zero Trust",
        "pl": "Zero Trust",
    },
    "rbac_adv": {
        "tr": "Gelişmiş RBAC",
        "fr": "RBAC avancé",
        "es": "RBAC avanzado",
        "it": "RBAC avanzato",
        "pl": "Zaawansowany RBAC",
    },
    "audit": {
        "tr": "Değiştirilemez Denetim İzleri",
        "fr": "Pistes d'audit immuables",
        "es": "Registros de auditoría inmutables",
        "it": "Audit trail immutabili",
        "pl": "Niemutowalne ślady audytu",
    },
    "mfa": {
        "tr": "MFA / 2FA",
        "fr": "MFA / 2FA",
        "es": "MFA / 2FA",
        "it": "MFA / 2FA",
        "pl": "MFA / 2FA",
    },
    "siem": {
        "tr": "SIEM Dışa Aktarımı",
        "fr": "Export SIEM",
        "es": "Exportación SIEM",
        "it": "Export SIEM",
        "pl": "Eksport SIEM",
    },
    "encryption": {
        "tr": "Şifreleme Katmanı",
        "fr": "Couche de chiffrement",
        "es": "Capa de cifrado",
        "it": "Livello crittografia",
        "pl": "Warstwa szyfrowania",
    },
    "ai_assistant": {
        "tr": "Yapay Zeka Asistanı",
        "fr": "Assistant IA",
        "es": "Asistente de IA",
        "it": "Assistente IA",
        "pl": "Asystent AI",
    },
    "ai_copilot": {
        "tr": "Yapay Zeka Copilot",
        "fr": "Copilote IA",
        "es": "Copiloto de IA",
        "it": "Copilota IA",
        "pl": "Copilot AI",
    },
    "predictive_att": {
        "tr": "Tahmine Dayalı Devam",
        "fr": "Présence prédictive",
        "es": "Asistencia predictiva",
        "it": "Presenza predittiva",
        "pl": "Predykcyjna obecność",
    },
    "fraud": {
        "tr": "Dolandırıcılık Tespiti",
        "fr": "Détection de fraude",
        "es": "Detección de fraude",
        "it": "Rilevamento frodi",
        "pl": "Wykrywanie oszustw",
    },
    "scheduling_ai": {
        "tr": "Yapay Zeka Vardiya Planlama",
        "fr": "Planification d'équipes IA",
        "es": "Planificación de turnos con IA",
        "it": "Pianificazione turni IA",
        "pl": "Planowanie zmian z AI",
    },
    "heatmap": {
        "tr": "İşgücü Isı Haritaları",
        "fr": "Heatmaps workforce",
        "es": "Mapas de calor de fuerza laboral",
        "it": "Heatmap workforce",
        "pl": "Mapy ciepła siły roboczej",
    },
    "nlq": {
        "tr": "Doğal Dil Sorguları",
        "fr": "Requêtes en langage naturel",
        "es": "Consultas en lenguaje natural",
        "it": "Query in linguaggio naturale",
        "pl": "Zapytania w języku naturalnym",
    },
    "ops_os": {
        "tr": "Fiziksel Operasyon İşletim Sistemi",
        "fr": "OS opérations physiques",
        "es": "Sistema operativo de operaciones físicas",
        "it": "OS operazioni fisiche",
        "pl": "System operacyjny operacji fizycznych",
    },
    "digital_twin": {
        "tr": "Dijital İkiz",
        "fr": "Jumeau numérique",
        "es": "Gemelo digital",
        "it": "Gemello digitale",
        "pl": "Cyfrowy bliźniak",
    },
    "site_intel": {
        "tr": "Saha Zekası",
        "fr": "Intelligence de chantier",
        "es": "Inteligencia de obra",
        "it": "Intelligence cantiere",
        "pl": "Inteligencja placu budowy",
    },
    "camera_ai": {
        "tr": "Kamera Zekası",
        "fr": "Intelligence caméra",
        "es": "Inteligencia de cámaras",
        "it": "Intelligence telecamere",
        "pl": "Inteligencja kamer",
    },
    "iot": {
        "tr": "IoT Altyapısı",
        "fr": "Infrastructure IoT",
        "es": "Infraestructura IoT",
        "it": "Infrastruttura IoT",
        "pl": "Infrastruktura IoT",
    },
    "emergency_ops": {
        "tr": "Acil Durum Zekası",
        "fr": "Intelligence d'urgence",
        "es": "Inteligencia de emergencias",
        "it": "Intelligence emergenze",
        "pl": "Inteligencja awaryjna",
    },
    "auto_rules": {
        "tr": "Otonom Kurallar",
        "fr": "Règles autonomes",
        "es": "Reglas autónomas",
        "it": "Regole autonome",
        "pl": "Autonomiczne reguły",
    },
    "self_heal": {
        "tr": "Kendi Kendini Onaran İşler",
        "fr": "Jobs auto-réparateurs",
        "es": "Trabajos de autorreparación",
        "it": "Job self-healing",
        "pl": "Zadania samonaprawcze",
    },
    "auto_incident": {
        "tr": "Otonom Olay Müdahalesi",
        "fr": "Réponse aux incidents autonome",
        "es": "Respuesta autónoma a incidentes",
        "it": "Risposta incidenti autonoma",
        "pl": "Autonomiczna reakcja na incydenty",
    },
    "payroll": {
        "tr": "Bordro Entegrasyonları",
        "fr": "Intégrations paie",
        "es": "Integraciones de nómina",
        "it": "Integrazioni payroll",
        "pl": "Integracje z płacami",
    },
    "sap": {
        "tr": "SAP Entegrasyonu",
        "fr": "Intégration SAP",
        "es": "Integración SAP",
        "it": "Integrazione SAP",
        "pl": "Integracja SAP",
    },
    "oracle": {
        "tr": "Oracle Entegrasyonu",
        "fr": "Intégration Oracle",
        "es": "Integración Oracle",
        "it": "Integrazione Oracle",
        "pl": "Integracja Oracle",
    },
    "m365": {
        "tr": "Microsoft 365",
        "fr": "Microsoft 365",
        "es": "Microsoft 365",
        "it": "Microsoft 365",
        "pl": "Microsoft 365",
    },
    "google": {
        "tr": "Google Workspace",
        "fr": "Google Workspace",
        "es": "Google Workspace",
        "it": "Google Workspace",
        "pl": "Google Workspace",
    },
    "webhooks": {
        "tr": "Webhooks",
        "fr": "Webhooks",
        "es": "Webhooks",
        "it": "Webhook",
        "pl": "Webhooki",
    },
    "api_gateway": {
        "tr": "API Gateway / v1",
        "fr": "Passerelle API / v1",
        "es": "Puerta de enlace API / v1",
        "it": "API Gateway / v1",
        "pl": "Bramka API / v1",
    },
    "sdk": {
        "tr": "SDK Altyapısı",
        "fr": "Infrastructure SDK",
        "es": "Infraestructura SDK",
        "it": "Infrastruttura SDK",
        "pl": "Infrastruktura SDK",
    },
    "marketplace": {
        "tr": "Entegrasyon Pazaryeri",
        "fr": "Marketplace d'intégrations",
        "es": "Marketplace de integraciones",
        "it": "Marketplace integrazioni",
        "pl": "Marketplace integracji",
    },
    "white_label": {
        "tr": "White-Label",
        "fr": "Marque blanche",
        "es": "Marca blanca",
        "it": "White label",
        "pl": "White label",
    },
    "public_api": {
        "tr": "Halka Açık Geliştirici API'leri",
        "fr": "API développeur publiques",
        "es": "API públicas para desarrolladores",
        "it": "API pubbliche per sviluppatori",
        "pl": "Publiczne API dla deweloperów",
    },
    "k8s": {
        "tr": "Kubernetes Uyumlu",
        "fr": "Compatible Kubernetes",
        "es": "Compatible con Kubernetes",
        "it": "Pronto per Kubernetes",
        "pl": "Gotowe na Kubernetes",
    },
    "postgres": {
        "tr": "PostgreSQL Kümeleme",
        "fr": "Clustering PostgreSQL",
        "es": "Clustering PostgreSQL",
        "it": "Clustering PostgreSQL",
        "pl": "Klastrowanie PostgreSQL",
    },
    "redis": {
        "tr": "Kuyruk / Redis",
        "fr": "File d'attente / Redis",
        "es": "Cola / Redis",
        "it": "Coda / Redis",
        "pl": "Kolejka / Redis",
    },
    "dr": {
        "tr": "Felaket Kurtarma",
        "fr": "Reprise après sinistre",
        "es": "Recuperación ante desastres",
        "it": "Disaster recovery",
        "pl": "Odtwarzanie po awarii",
    },
    "obs": {
        "tr": "Gözlemlenebilirlik Yığını",
        "fr": "Stack d'observabilité",
        "es": "Stack de observabilidad",
        "it": "Stack osservabilità",
        "pl": "Stos obserwowalności",
    },
    "multi_region": {
        "tr": "Çok Bölgeli Dağıtım",
        "fr": "Multi-région",
        "es": "Multi-región",
        "it": "Multi-regione",
        "pl": "Wiele regionów",
    },
    "billing": {
        "tr": "Kurumsal Faturalama",
        "fr": "Facturation entreprise",
        "es": "Facturación empresarial",
        "it": "Fatturazione enterprise",
        "pl": "Fakturowanie enterprise",
    },
    "dunning_b": {
        "tr": "Tahsilat Otomasyonu",
        "fr": "Automatisation des relances",
        "es": "Automatización de cobros",
        "it": "Automazione solleciti",
        "pl": "Automatyzacja windykacji",
    },
    "plans": {
        "tr": "Çok Planlı SaaS",
        "fr": "SaaS multi-offres",
        "es": "SaaS multiplan",
        "it": "SaaS multi-piano",
        "pl": "SaaS wieloplanowy",
    },
    "command": {
        "tr": "İşgücü Komuta Merkezi",
        "fr": "Centre de commande workforce",
        "es": "Centro de mando de fuerza laboral",
        "it": "Centro comando workforce",
        "pl": "Centrum dowodzenia siły roboczej",
    },
    "global_ready": {
        "tr": "Küresel Hazırlık",
        "fr": "Prêt pour le global",
        "es": "Preparación global",
        "it": "Pronto per il globale",
        "pl": "Gotowość globalna",
    },
    "catalog": {
        "tr": "Kurumsal Katalog",
        "fr": "Catalogue entreprise",
        "es": "Catálogo empresarial",
        "it": "Catalogo enterprise",
        "pl": "Katalog enterprise",
    },
    "wf_os": {
        "tr": "İşgücü İşletim Sistemi",
        "fr": "Système d'exploitation workforce",
        "es": "Sistema operativo de fuerza laboral",
        "it": "Sistema operativo workforce",
        "pl": "System operacyjny siły roboczej",
    },
    "ai_cloud": {
        "tr": "AI İşgücü Bulutu",
        "fr": "Cloud workforce IA",
        "es": "Nube de fuerza laboral con IA",
        "it": "Cloud workforce IA",
        "pl": "Chmura AI siły roboczej",
    },
}

SURFACE_LABEL_EXTRA: dict[str, dict[str, str]] = {
    "legacy": {
        "tr": "Legacy Portal",
        "fr": "Portail legacy",
        "es": "Portal legacy",
        "it": "Portale legacy",
        "pl": "Portal legacy",
    },
    "admin-v2": {
        "tr": "Admin v2",
        "fr": "Admin v2",
        "es": "Admin v2",
        "it": "Admin v2",
        "pl": "Admin v2",
    },
    "worker": {
        "tr": "Worker Uygulaması",
        "fr": "Application Worker",
        "es": "App Worker",
        "it": "App Worker",
        "pl": "Aplikacja Worker",
    },
    "hub": {
        "tr": "Kurumsal Hub",
        "fr": "Hub entreprise",
        "es": "Hub empresarial",
        "it": "Hub enterprise",
        "pl": "Hub enterprise",
    },
    "api": {
        "tr": "Yalnızca API",
        "fr": "API uniquement",
        "es": "Solo API",
        "it": "Solo API",
        "pl": "Tylko API",
    },
    "config": {
        "tr": "Yapılandırma",
        "fr": "Configuration",
        "es": "Configuración",
        "it": "Configurazione",
        "pl": "Konfiguracja",
    },
}

NOTE_EXTRA: dict[str, dict[str, str]] = {
    "dunning": {
        "tr": "Arka plan işi — Redis performansı artırır",
        "fr": "Tâche en arrière-plan — Redis améliore le débit",
        "es": "Trabajo en segundo plano — Redis mejora el rendimiento",
        "it": "Job in background — Redis migliora le prestazioni",
        "pl": "Zadanie w tle — Redis poprawia wydajność",
    },
    "self_heal": {
        "tr": "Redis + worker süreci gerektirir",
        "fr": "Nécessite Redis + processus worker",
        "es": "Requiere Redis + proceso worker",
        "it": "Richiede Redis + processo worker",
        "pl": "Wymaga Redis + procesu worker",
    },
    "dunning_b": {
        "tr": "Arka plan işi",
        "fr": "Tâche en arrière-plan",
        "es": "Trabajo en segundo plano",
        "it": "Job in background",
        "pl": "Zadanie w tle",
    },
    "wf_os": {
        "tr": "Vizyon — katmanlar 1–15 arasında birleştirme",
        "fr": "Vision — agrégation sur les couches 1–15",
        "es": "Visión — agregación entre capas 1–15",
        "it": "Visione — aggregazione tra i livelli 1–15",
        "pl": "Wizja — agregacja między warstwami 1–15",
    },
    "ai_cloud": {
        "tr": "OPENAI_API_KEY + zeka katmanı",
        "fr": "OPENAI_API_KEY + couche intelligence",
        "es": "OPENAI_API_KEY + capa de inteligencia",
        "it": "OPENAI_API_KEY + livello intelligence",
        "pl": "OPENAI_API_KEY + warstwa intelligence",
    },
}
