apiVersion: v1
kind: Service
metadata:
  name: {{ include "baupass.fullname" . }}-api
  labels:
    {{- include "baupass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "baupass.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.port }}
